Repository openshift/oc, pull requests merged in 2019-11, with the labels that each got.

#126 mirror: Support mirroring to disk as a target
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/image/image.go
  pkg/cli/image/info/info.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/file.go
  pkg/cli/image/mirror/mappings.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/mirror/plan.go
  pkg/cli/image/serve/serve.go
Labels: approved, lgtm, size/XXL

#140 Fix `oc adm catalog`
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-registry/pkg/api/grpc_health_v1/health.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/builder_options.go
  vendor/github.com/operator-framework/operator-registry/pkg/client/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/conversion.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/empty.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/001_related_images.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/002_bundle_path.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/003_required_apis.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrator.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#139 image: Image commands should all support file targets
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/build.go
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
  pkg/cli/image/append/append.go
  pkg/cli/image/extract/extract.go
  pkg/cli/image/imagesource/file.go
  pkg/cli/image/imagesource/options.go
  pkg/cli/image/imagesource/reference.go
  pkg/cli/image/imagesource/s3.go
  pkg/cli/image/info/info.go
  pkg/cli/image/mirror/mappings.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/mirror/plan.go
Labels: approved, lgtm, size/XL

#143 Improve release to work better for disconnected
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/image/imagesource/dryrun.go
  pkg/cli/image/imagesource/options.go
  pkg/cli/image/imagesource/reference.go
  pkg/cli/image/info/info.go
  pkg/cli/image/mirror/mappings.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/registry/login/login.go
Labels: approved, lgtm, size/XL

#147 Bug 1725977: admin/release/new: always consider all mappings
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#150 Bug 1767675: fix debug's comment
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#138 Bug 1767163: fix app.kubernetes.io/name to use just IS name
  pkg/cli/newapp/newapp.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#135 Bug 1763807: print detailed error to user when getting node logs
  pkg/cli/admin/node/logs.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#152 Update ruby-22-centos7 to ruby-25-centos7
  pkg/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
  pkg/cli/admin/buildchain/test/multiple-trigger-bcs.yaml
  pkg/cli/admin/buildchain/test/single-namespace-bcs.yaml
  pkg/cli/kubectlwrappers/wrappers.go
  pkg/helpers/describe/chaindescriber_test.go
  pkg/helpers/describe/projectstatus_test.go
  pkg/helpers/graph/genericgraph/test/bare-bc.yaml
  pkg/helpers/graph/genericgraph/test/bare-dc.yaml
  pkg/helpers/graph/genericgraph/test/circular-not.yaml
  pkg/helpers/graph/genericgraph/test/circular.yaml
  pkg/helpers/graph/genericgraph/test/deployment.yaml
  pkg/helpers/graph/genericgraph/test/failed-build.yaml
  pkg/helpers/graph/genericgraph/test/missing-istag.yaml
  pkg/helpers/graph/genericgraph/test/new-app.yaml
  pkg/helpers/graph/genericgraph/test/new-project-deployed-app.yaml
  pkg/helpers/graph/genericgraph/test/new-project-no-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-one-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-two-deployment-configs.yaml
  pkg/helpers/graph/genericgraph/test/pushable-build.yaml
  pkg/helpers/graph/genericgraph/test/unpushable-build-2.yaml
  pkg/helpers/graph/genericgraph/test/unpushable-build.yaml
  pkg/helpers/newapp/app/imageref_test.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, size/L

#151 Improve errors in inspect
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/resource.go
Labels: approved, lgtm, size/S

#136 Bug 1759920: Fixed Dockerfile FROM statement parser.
  pkg/helpers/newapp/docker/dockerfile/dockerfile.go
  pkg/helpers/newapp/docker/dockerfile/dockerfile_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#156 Bug 1748777: oc: don't print usage info if pass a bad flag, only suggest to pass --help
  pkg/helpers/cmd/templater.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#155 Bug 1768516: fix extracted-oc adm extract oc
  pkg/cli/admin/release/extract_tools.go
  pkg/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#157 image: If a user specifies both tag and digest, retrieve via digest
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mappings.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm, size/S

#145 Bug 1713263: pkg/cli/admin/upgrade: allow users to force when updating to latest
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#121 Bug 1759185: clarify upgrade's force flag description
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#164 Bug 1763929: Set TypeSetter in get print flags, like we do everywhere elsewhere
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/chai2010/gettext-go/gettext/hello.go
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/gonum/matrix/gendoc.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/samples/install.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/api/samples/v1/doc.go
  vendor/github.com/openshift/api/samples/v1/generated.pb.go
  vendor/github.com/openshift/api/samples/v1/generated.proto
  vendor/github.com/openshift/api/samples/v1/register.go
  vendor/github.com/openshift/api/samples/v1/types_config.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#160 Bug 1770144: fix imagestream parsing to properly split its namespace part
  pkg/cli/newapp/newapp.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#161 Bug 1771329: only build adm catalog command for linux
  pkg/cli/admin/admin.go
  pkg/cli/admin/catalog/catalog.go
  pkg/cli/admin/catalog/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#153 Enable all Linux arches in cli-artifacts
  Makefile
  images/cli-artifacts/Dockerfile.rhel
  oc.spec
Labels: approved, lgtm, ok-to-test, size/S

#171 Bug 1774642: Avoid hard links in cli-artifacts
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#170 Bug 1774318: use a fips compliant oc new-app example with the new-project message
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#182 Bug 1776100: don't install quota CRDs
  cmd/oc/oc.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
