Repository openshift/oc, pull requests merged in 2019-08, with the labels that each got.

#6 release/mirror: Add examples for using the new mirror
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, size/M

#40 Bug 1671685: remove-(cluster-)role-from-*: Properly report binding kind if not found
  pkg/cli/admin/policy/modify_roles.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#41 Bug 1707679: Don't install CRD SCC types into global scheme
  cmd/oc/oc.go
  cmd/oc/oc_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#37 Bug 1735404: `oc extract` should print binaryData as well
  pkg/cli/extract/extract.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#21 support multiple images and image streams
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, size/L

#45 Bug 1669657 - Add --boot option to oc adm node-logs
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/node/logs.go
Labels: approved, lgtm, size/S

#63 Bug 1737657 - bump(*)
  glide.lock
  vendor/github.com/containerd/continuity/fs/fstest/compare.go
  vendor/github.com/containerd/continuity/fs/fstest/compare_windows.go
  vendor/github.com/containerd/continuity/fs/fstest/continuity_util.go
  vendor/github.com/docker/libtrust/README.md
  vendor/github.com/docker/libtrust/util.go
  vendor/github.com/gorilla/mux/.circleci/config.yml
  vendor/github.com/gorilla/mux/.github/stale.yml
  vendor/github.com/gorilla/mux/.travis.yml
  vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/example_cors_method_middleware_test.go
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/middleware_test.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/mux_test.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/main.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/golang.org/x/time/CONTRIBUTING.md
  vendor/golang.org/x/time/README
  vendor/golang.org/x/time/README.md
  vendor/golang.org/x/time/go.mod
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/rate_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/get_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/version/patch_version.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/version/version.go
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
Labels: approved, lgtm, size/XXL

#43 Bug 1737127: idle: fix null dereference when pod's controller can't be found
  pkg/cli/idle/idle.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#57 pkg/cli/admin/release: support extracting baremetal installer
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, size/M

#66 Add --force when linking other oc binaries
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#64 Bug 1734504: Parts of oc adm must-gather do not respect --config CLI option
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/rsync/copy_rsync.go
  pkg/cli/rsync/copy_rsync_test.go
  pkg/cli/rsync/rsync.go
  pkg/helpers/cmd/sibling.go
  pkg/helpers/cmd/sibling_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#44 Bug 1737392: Hide sort-by flag from new-build help
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/newbuild/newbuild.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#60 remove aggregateErrorOrNil func
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/S

#68 Bug 1744289: sort available updates when printing
  pkg/cli/admin/upgrade/upgrade.go
  pkg/cli/admin/upgrade/upgrade_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#48 Bug 1704827: Improve error msg when console URL passed to login via CLI
  pkg/cli/login/error_translation.go
  pkg/cli/login/helpers.go
  pkg/cli/login/loginoptions.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#72 release: Allow --exclude to work for --from-release in release
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#73 Fix GO_PACKAGE detection
  glide.lock
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/fstest/file.go
  vendor/github.com/containerd/continuity/fs/fstest/testsuite.go
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/mux_test.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/quota/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/scripts/doc.go
  vendor/github.com/openshift/library-go/pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
  vendor/github.com/openshift/library-go/pkg/operator/watchdog/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/watchdog/cmd_test.go
  vendor/golang.org/x/time/CONTRIBUTING.md
  vendor/golang.org/x/time/README
  vendor/golang.org/x/time/README.md
  vendor/golang.org/x/time/go.mod
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/rate_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/get_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/sorter.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/table_printer.go
  vendor/k8s.io/kubernetes/pkg/kubectl/scheme/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/scheme/install.go
  vendor/k8s.io/kubernetes/pkg/printers/humanreadable.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_test.go
Labels: approved, lgtm, size/XXL

#71 Bug 1739445: Fix oc rpm for ART builds
  Makefile
  oc.spec
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#74 Fix kubectl in rpm
  oc.spec
Labels: approved, lgtm, size/S

#77 Cleanup spec
  oc.spec
Labels: approved, lgtm, size/M

#69 Bug 1610599: Remove RunE usage from oc
  pkg/cli/admin/release/release.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
