Repository openshift/oc, pull requests merged in 2019-09, with the labels that each got.

#75 Bug 1709239: Remove Git Repo option from 'oc set volumes' cmd
  pkg/cli/set/env.go
  pkg/cli/set/probe.go
  pkg/cli/set/triggers.go
  pkg/cli/set/volume.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#81 release: Fix verification errors when excluding components
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#83 Bug 1748372: oc adm must-gather must prefix lines from stdout and stderr
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#82 debug: Improve docs of oc debug command to mention nodes
  pkg/cli/debug/debug.go
Labels: approved, lgtm, size/M

#85 release: Add a better error message when base tag missing
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#87 Fix oc version to report proper information
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/version/version.go
Labels: approved, lgtm, size/M

#49 Fixup the following crash
  pkg/cli/secrets/sshauth.go
Labels: approved, lgtm, ok-to-test, size/XS

#84 oc adm must-gather should always write output to sub dir
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/S

#92 Bump
  glide.lock
  vendor/github.com/google/btree/btree_test.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/convert/convert.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/convert/patch_convert_openshift.go
Labels: approved, lgtm, size/L

#62 Bug 1728111 - update oc adm node-logs with information about tail line limits
  pkg/cli/admin/node/logs.go
Labels: approved, lgtm, size/XS

#90 cli: Add `oc set data` that makes it easy to manipulate secrets/config maps
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/lib/init.sh
  hack/update-generated-completions.sh
  hack/verify-generated-completions.sh
  pkg/cli/set/data.go
  pkg/cli/set/set.go
Labels: approved, lgtm, size/XL

#53 fix bug 1725027: --output flag to release info does not include all options
  pkg/cli/admin/release/info.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#80 Deprecate oc adm migrate
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/migrate/etcd/ttl.go
  pkg/cli/admin/migrate/images/imagerefs.go
  pkg/cli/admin/migrate/legacyhpa/hpa.go
  pkg/cli/admin/migrate/migrate.go
  pkg/cli/admin/migrate/storage/storage.go
  pkg/cli/admin/migrate/templateinstances/templateinstances.go
Labels: approved, lgtm, size/XL

#97 Update deprecation message & drop it from oc adm migrate template-instance
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/migrate/etcd/ttl.go
  pkg/cli/admin/migrate/images/imagerefs.go
  pkg/cli/admin/migrate/legacyhpa/hpa.go
  pkg/cli/admin/migrate/migrate.go
  pkg/cli/admin/migrate/storage/storage.go
  pkg/cli/admin/migrate/templateinstances/templateinstances.go
Labels: approved, lgtm, size/L

#95 pkg/cli/admin/release/mirror: Conditional printImageContentInstructions
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, size/S

#96 release: Add `--commit-urls` to the release info command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, size/M

#107 Add oc adm inspect command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/admin.go
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/inspect_test.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/pod_readiness.go
  pkg/cli/admin/inspect/port_forward.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/route.go
  pkg/cli/admin/inspect/secret.go
  pkg/cli/admin/inspect/util.go
  pkg/cli/admin/inspect/writer.go
Labels: approved, lgtm, size/XXL

#108 Bump to kubernetes 1.16.0
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/k8s.io/kubernetes/pkg/kubectl/.import-restrictions
  vendor/k8s.io/kubernetes/pkg/kubectl/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubectl/doc.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#113 Bug 1756107: Make container endpoint collection errors non-fatal
  pkg/cli/admin/inspect/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
