Repository openshift/oc, pull requests merged in 2019-07, with the labels that each got.

#7 Add new cli images and fix cli rhel image
  images/cli/Dockerfile
  images/cli/Dockerfile.rhel
  images/deployer/Dockerfile.rhel
  images/recycler/Dockerfile.rhel
Labels: lgtm, size/S

#8 Install missing dependencies on OCP build
  images/cli/Dockerfile
  images/cli/Dockerfile.rhel
Labels: size/XS

#11 Fix images
  Makefile
  images/cli/Dockerfile
  images/cli/Dockerfile.rhel
Labels: lgtm, size/S

#13 Cosmetics
  Makefile
Labels: size/XS

#17 Set the same tags as origin did
  Makefile
Labels: lgtm, size/XS

#18 quick and dirty way to get a kubectl version
  Makefile
Labels: approved, lgtm, size/XS

#16 Make sure packages are installed
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#24 Add tnozicka
  OWNERS
Labels: approved, lgtm, size/XS

#26 describe: print empty image config fields if the docker config is nil
  pkg/helpers/describe/describer.go
Labels: approved, lgtm, size/S

#27 add cli tools
  .gitignore
  Makefile
  contrib/completions/bash/.files_generated
  contrib/completions/bash/oc
  contrib/completions/zsh/.files_generated
  contrib/completions/zsh/oc
  hack/lib/init.sh
  hack/update-generated-completions.sh
  hack/verify-generated-completions.sh
  tools/clicheck/OWNERS
  tools/clicheck/check_cli_conventions.go
  tools/clicheck/sanity/cmd_sanity.go
  tools/gendocs/OWNERS
  tools/gendocs/gen_openshift_docs.go
  tools/gendocs/gendocs/gendocs.go
  tools/genman/OWNERS
  tools/genman/gen_man.go
  tools/genman/md2man/md2man.go
  tools/genman/md2man/roff.go
Labels: approved, lgtm, size/XXL

#5 Extend version cmd
  pkg/cli/cli.go
  pkg/cli/deployer/deployer.go
  pkg/cli/deployer/version.go
  pkg/cli/kubectlwrappers/wrappers.go
  pkg/cli/shim_kubectl.go
  pkg/cli/version/version.go
Labels: approved, lgtm, size/L

#31 Fix kubernetes git version in ART build
  Makefile
Labels: approved, lgtm, size/XS

#28 Makefile: remove no_openssl
  Makefile
Labels: approved, lgtm, size/XS
