Repository openshift/oc, pull requests merged in 2019-12, with the labels that each got.

#185 Bug 1777030: Update support tools container image
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#195 Bug 1771420: Update ruby-22-centos7 to ruby-25-centos7
  pkg/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
  pkg/cli/admin/buildchain/test/multiple-trigger-bcs.yaml
  pkg/cli/admin/buildchain/test/single-namespace-bcs.yaml
  pkg/cli/kubectlwrappers/wrappers.go
  pkg/helpers/describe/chaindescriber_test.go
  pkg/helpers/describe/projectstatus_test.go
  pkg/helpers/graph/genericgraph/test/bare-bc.yaml
  pkg/helpers/graph/genericgraph/test/bare-dc.yaml
  pkg/helpers/graph/genericgraph/test/circular-not.yaml
  pkg/helpers/graph/genericgraph/test/circular.yaml
  pkg/helpers/graph/genericgraph/test/deployment.yaml
  pkg/helpers/graph/genericgraph/test/failed-build.yaml
  pkg/helpers/graph/genericgraph/test/missing-istag.yaml
  pkg/helpers/graph/genericgraph/test/new-app.yaml
  pkg/helpers/graph/genericgraph/test/new-project-deployed-app.yaml
  pkg/helpers/graph/genericgraph/test/new-project-no-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-one-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-two-deployment-configs.yaml
  pkg/helpers/graph/genericgraph/test/pushable-build.yaml
  pkg/helpers/graph/genericgraph/test/unpushable-build-2.yaml
  pkg/helpers/graph/genericgraph/test/unpushable-build.yaml
  pkg/helpers/newapp/app/imageref_test.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#167 Bug 1775875: pkg/cli/admin/release/extract_tools: Pass []replacements to copyAndReplace
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/extract_tools_test.go
  pkg/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#177 Bug 1748061: copy gotdotenv and add ability to override underlying scanner buffer …
  pkg/helpers/newapp/app/env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#169 Wire in `oc rollout restart` from kubectl
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/rollout/rollout.go
Labels: approved, lgtm, size/L

#168 Bug 1773807: Enable all Linux arches in cli-artifacts [4.2]
  Makefile
  images/cli-artifacts/Dockerfile.rhel
  oc.spec
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#166 Bug 1779331: Fix a number of issues around debugging daemonset pods and init containers
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#201 Revert "Bug 1777030: Update support tools container image"
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#202 Revert "Bug 1777031: Update support tools container image"
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#165 Bug 1773257: pkg/cli/admin/release/extract_tools: Inject release version into installer
  pkg/cli/admin/release/extract_tools.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#50 Get rid of unnecessary conversions
  pkg/cli/admin/policy/subject_review.go
  pkg/cli/debug/debug.go
  pkg/cli/process/process.go
Labels: approved, lgtm, size/M

#207 make inspect more resilient and slightly faster
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, size/M

#132 Clean kubectl wrappers
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, lgtm, size/L

#214 [release-4.2] Bug 1776495: don't install quota CRDs
  cmd/oc/oc.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#216 test: Fix describer test to exclude extra types
  pkg/helpers/describe/describer_test.go
Labels: approved, lgtm, size/S

#209 Bug 1783055: Allow 'machine-os' to register itself and provide display name
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/annotations.go
  pkg/cli/admin/release/image_mapper.go
  pkg/cli/admin/release/image_mapper_test.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/info_test.go
  pkg/cli/admin/release/new.go
  pkg/cli/admin/release/test/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#181 Bug 1772942: Fix ignored `--manifest-dir` option in `oc adm catalog build`
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/apprclient/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/builder.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/builder_options.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/manifest_downloader.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/command.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/getimagedata_options.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/imagereader.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/labelreader.go
  vendor/github.com/operator-framework/operator-registry/pkg/mirror/mirror.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/bundle.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/csv.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/directory.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/image.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/000_init.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/001_related_images.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/002_bundle_path.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/003_required_apis.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/004_cascade_delete.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/005_version_skiprange.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrator.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/remove.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#220 release: Fix component version display in changelog
  pkg/cli/admin/release/image_mapper.go
Labels: approved, lgtm, size/XS

#224 Bug 1784755: set insecure-skip-tls-verify-backend flag
  pkg/cli/logs/logs.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#212 Add security options to `oc adm catalog` commands
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/build.go
  pkg/cli/admin/catalog/mirror.go
Labels: approved, lgtm, size/L

#213 Bug 1780714: add --insecure-registries to oc new-build
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/newbuild/newbuild.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#226 oc set serviceacount: fix help statements
  pkg/cli/set/set.go
Labels: approved, lgtm, ok-to-test, size/XS

#227 Bug 1785513: fix describe for HPA
  pkg/helpers/describe/deployments.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
