Repository openshift/oc, pull requests merged in 2019-10, with the labels that each got.

#114 inspect: collect /debug/pprof data
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, size/S

#105 release: Strip leading bracket indicators from changelogs
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/git_test.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, size/L

#112 Bug 1754042: Retry 429 and 503 errors in registry client
  go.mod
  go.sum
  pkg/cli/image/manifest/manifest.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/tmp.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/yq.mk
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#111 Bug 1756454: Separate upgrade flags for safety instead of abusing force
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#109 Bug 1756453: Separate upgrade flags for safety instead of abusing force
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#117 Bug 1540560: fix oc status for daemonsets
  pkg/helpers/describe/projectstatus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#116 Bug 1542325: ignore pods when giving liveness suggestions
  pkg/helpers/graph/kubegraph/analysis/podspec.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#88 Bug 1715001: If extracted from payload, 'oc version' reports payload version
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/extract_tools_test.go
  pkg/cli/version/version.go
  pkg/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#94 pkg/cli/admin/release/mirror: Fix "exapmles" -> "examples" comment typo
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, size/XS

#118 fix(inspect): changes --base-dir flag to --dest-dir
  pkg/cli/admin/inspect/inspect.go
Labels: approved, lgtm, size/XS

#119 mirror: Include version inside the default target tag
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, size/M

#104 pkg/cli/image/extract: disable pigz to prevent race condition
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, size/XS

#120 mirror: Add --to-dir to release mirror, uses skopeo to archive
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, size/M

#100 Corrects error message
  pkg/cli/newapp/newapp.go
Labels: approved, lgtm, size/XS

#101 Align oc new-app generate labels with recommended label
  pkg/cli/newapp/newapp.go
Labels: approved, lgtm, size/S

#124 image-mirror: Manifest list manifests have to be copied
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/mirror/plan.go
Labels: approved, lgtm, size/L

#125 Bug 1760269: UPSTREAM: 77874: fix CVE-2019-11244: kubectl --http-cache=<world-accessible dir>
  glide.lock
  glide.yaml
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/seq_test.go
  vendor/github.com/google/uuid/sql_test.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/uuid_test.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/register.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/types.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/register.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/types.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/tmp.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/yq.mk
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/build.go
  vendor/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/rebuild.go
  vendor/github.com/openshift/source-to-image/test/integration/docker/integration_test.go
  vendor/github.com/openshift/source-to-image/test/integration/dockerfile/dockerfile_test.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/bytes_test.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int_test.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/string_to_string_test.go
  vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery.go
  vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery_test.go
  vendor/k8s.io/client-go/discovery/cached/disk/round_tripper.go
  vendor/k8s.io/client-go/discovery/cached/disk/round_tripper_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#130 cmd/oc: disable docker's use of pigz earlier
  cmd/oc/oc.go
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, size/XS

#123 registry-login: Allow login with credentials
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/registry/login/login.go
Labels: approved, lgtm, size/M

#129 Switch inspect to use unstructured when reading .status.relatedObjects
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm, size/L

#131 Bug 1763728: fix 'oc adm release extract' version injection
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/extract_tools_test.go
  pkg/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
