Repository openshift/oc, pull requests merged in 2020-04, with the labels that each got.

#361 image/mirror: Allow `--continue-on-error` for mirror
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/image/mirror/mirror.go
Labels: approved, lgtm

#362 image/mirror: Upconvert v1 schemas to v2 schemas by default
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm

#369 debug: The `--dry-run` flag does not work with debug
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#368 debug: Correctly default the tools image now that it is on the cluster
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#375 oc rsh: properly shadow position of --
  pkg/cli/rsh/rsh.go
Labels: approved, lgtm

#367 Add BZ component name to OWNERS
  OWNERS
Labels: approved, lgtm

#376 Bug 1821648: Zeroing BearerTokenFile for prune
  pkg/cli/admin/prune/images/images.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#386 make unit tests not ask for gpg store password
  pkg/helpers/source-to-image/git/testhelpers.go
Labels: approved, lgtm

#380 Bug 1819688: login: choose the CAs based on the remote server cert
  pkg/cli/login/loginoptions_test.go
  pkg/helpers/tokencmd/request_token.go
  pkg/helpers/tokencmd/request_token_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#374 Add make oc target
  Makefile
Labels: approved, lgtm

#343 Implement enhancements/oc/mirroring-release-signatures
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  go.mod
  go.sum
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/helpers/release/configmap.go
  pkg/helpers/release/configmap_test.go
  pkg/helpers/release/testdata/keyrings/combined.txt
  pkg/helpers/release/testdata/keyrings/redhat.txt
  pkg/helpers/release/testdata/keyrings/simple.txt
  pkg/helpers/release/testdata/signatures-2/.gitkeep
  pkg/helpers/release/testdata/signatures/sha256=e3f12513a4b22a2d7c0e7c9207f52128113758d9d68c7d06b11a0ac7672966f7/signature-1
  pkg/helpers/release/testdata/signatures/sha256=edd9824f0404f1a139688017e7001370e2f3fbc088b94da84506653b473fe140/signature-1
  pkg/helpers/release/verify.go
  pkg/helpers/release/verify_test.go
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#373 Bug 1825791: Fix a large number of silly things in login
  pkg/cli/login/loginoptions.go
  pkg/cli/project/project.go
  pkg/helpers/kubeconfig/smart_merge.go
  pkg/helpers/project/whoami.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#354 Bug 1825809: create: Add the bare minimum `oc create build`
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/create/build.go
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#392 Bug 1825565: pkg/cli/admin/release/mirror: Allow --apply-release-image-signature and --release-image-signature-to-dir
  pkg/cli/admin/release/mirror.go
  pkg/helpers/release/configmap.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#387 Bug 1826533: pkg/cli/admin/upgrade: Warn when --force is used
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#391 pkg/cli/admin/upgrade: Delegate to update-approvers
  OWNERS_ALIASES
  pkg/cli/admin/upgrade/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#388 Bug 1826533: pkg/cli/admin/upgrade: Warn when --allow-explicit-upgrade let you through
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#308 [release-4.2] Bug 1802895: bump(github.com/mtrmac/gpgme): v0.1.2
  glide.lock
  glide.yaml
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/examples/decrypt.go
  vendor/github.com/mtrmac/gpgme/examples/encrypt.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/gpgme_test.go
  vendor/github.com/mtrmac/gpgme/testdata/gpghome/gpg-agent.conf
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#401 Bug 1828194: wire printer flags to oc adm group sync
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/groups/sync/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#377 Bug 1821356: fix comment
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/valid-bug, lgtm

#310 Bug 1828280: Drop deprecated commands and flags
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/importer/appjson/appjson.go
  pkg/cli/importer/import.go
  pkg/cli/newapp/newapp.go
  pkg/cli/newbuild/newbuild.go
  pkg/cli/policy/cani/cani.go
  pkg/cli/policy/policy.go
  pkg/cli/process/process.go
  pkg/cli/set/deploymenthook.go
  pkg/cli/set/volume.go
  pkg/cli/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/XL

#396 Bug 1827061: add missing newline
  pkg/cli/admin/policy/modify_roles.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
