Repository openshift/oc, pull requests merged in 2020-02, with the labels that each got.

#279 Bug 1793267: Add verify-deps target
  Makefile
  vendor/github.com/getsentry/raven-go/Dockerfile.test
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#233 Bug 1774366: Squash oc logs on top upstream logs command
  go.mod
  go.sum
  pkg/cli/cli.go
  pkg/cli/logs/logs.go
  pkg/cli/logs/logs_test.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#281 Bug 1798622: oc adm release info: escape PR titles which might contain html
  pkg/cli/admin/release/git.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#286 Bug 1799075: Build machinery
  Makefile
  go.mod
  go.sum
  pkg/dependencymagnet/doc.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/doc.go
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/doc.go
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/help.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/openshift/build-machinery-go/scripts/doc.go
  vendor/github.com/openshift/build-machinery-go/scripts/update-deps.sh
  vendor/github.com/openshift/library-go/alpha-build-machinery/OWNERS
  vendor/github.com/openshift/library-go/alpha-build-machinery/doc.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#285 Bug 1798961: correct the example info
  pkg/cli/admin/catalog/build.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#271 Bug 1789266: remove deprecated oc secret sub-commands
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/cli.go
  pkg/cli/kubectl_compat_test.go
  pkg/cli/secrets/basicauth.go
  pkg/cli/secrets/basicauth_test.go
  pkg/cli/secrets/bsFixtures/dir/www.testing.com
  pkg/cli/secrets/bsFixtures/dirContainsMany/www.example.com
  pkg/cli/secrets/bsFixtures/dirContainsMany/www.otherexample.com
  pkg/cli/secrets/bsFixtures/dirNoSubdir/www.testing.com
  pkg/cli/secrets/bsFixtures/invalid/invalid-DNS
  pkg/cli/secrets/bsFixtures/leadingdot/.dockercfg
  pkg/cli/secrets/bsFixtures/leadingdot/.gitconfig
  pkg/cli/secrets/bsFixtures/multiple/www.google.com
  pkg/cli/secrets/bsFixtures/valid/ca.crt
  pkg/cli/secrets/bsFixtures/valid/ssh-privatekey
  pkg/cli/secrets/bsFixtures/www.google.com
  pkg/cli/secrets/dockercfg.go
  pkg/cli/secrets/known_secret_types.go
  pkg/cli/secrets/link.go
  pkg/cli/secrets/new.go
  pkg/cli/secrets/new_test.go
  pkg/cli/secrets/secrets.go
  pkg/cli/secrets/sshauth.go
  pkg/cli/secrets/sshauth_test.go
  pkg/cli/secrets/subcommand.go
  pkg/cli/secrets/unlink.go
  tools/clicheck/check_cli_conventions.go
  tools/gendocs/gen_openshift_docs.go
  tools/genman/gen_man.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#289 Bug 1801253: Enforce golang only at 1.13.4 level
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#278 [release-4.3] Bug 1797730: Mirror images one by one for oc adm catalog mirror
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/M

#292 Bug 1762692: Bump kubectl 1.17
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/describe/versioned/describe.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#275 Bug 1746149: fix tag creation when imagestreamtags are not accessible
  pkg/cli/tag/tag.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#211 Bug 1779353: Verify outbound manifests now that schema1 support is dropped
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#243 Bug 1788016: Suppress nil pointer dereference for job spec
  pkg/helpers/describe/projectstatus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#291 Bug 1801064: Deprecate Pipelines in new-app/build
  pkg/cli/newapp/newapp.go
  pkg/cli/newbuild/newbuild.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#277 Bug 1771552: Bug 1771553: Bug 1771549: Bug 1798549: oc debug
  pkg/cli/debug/debug.go
  pkg/helpers/conditions/conditions.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#295 Bug 1755428: improve error msgs in must-gather in case of must-gather pod not found
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#298 Bug 1800674: Option to force RepoDigest mirror
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#282 adm release info: refactor to build messages in order
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, size/M

#258 Add timeout option for must-gather as a optional parameter
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/S

#299 Bug 1801064: Add '\n' for pipeline deprecate info
  pkg/cli/newapp/newapp.go
  pkg/cli/newbuild/newbuild.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#305 Bug 1802872: bump(github.com/mtrmac/gpgme): v0.1.2
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#296 Bug 1797026: [CLI] oc adm catalog build neither support "-a, --registry-config=" flag, nor uses podman registry credentials file
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/build.go
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#306 Bug 1804609: bump(github.com/mtrmac/gpgme): v0.1.2
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#248 Bug 1789869: allow --config and --kubeconfig
  glide.lock
  glide.yaml
  pkg/cli/kubectlwrappers/wrappers.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/config/config.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#321 release: Add template output options for release info
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, size/M

#318 override FileDir with FromFileDir if set in Complete
  pkg/cli/image/mirror/mirror.go
Labels: approved, lgtm, size/XS

#319 Bug 1801285: set nodeName for debug pod only when explicitly set
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#303 Bug 1800464: fix(catalog): use registry image from openshift quay namespace
  pkg/cli/admin/catalog/build.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#320 Bug 1806779: Allow a file:// release argument to release mirror
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#329 Bug 1790785: bump(operator-framework/operator-registry)
  go.mod
  go.sum
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/operator-framework/operator-registry/pkg/apprclient/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/apprclient/metadata.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/appregistry.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/builder.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/downloader.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/input.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/command.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/imagereader.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/empty.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/image.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/CODE-OF-CONDUCT.md
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/GOVERNANCE.md
  vendor/google.golang.org/grpc/MAINTAINERS.md
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#331 [release 4.4] Bug 1804554: bump(operator-framework/operator-registry)
  go.mod
  go.sum
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/operator-framework/operator-registry/pkg/apprclient/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/apprclient/metadata.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/appregistry.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/builder.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/downloader.go
  vendor/github.com/operator-framework/operator-registry/pkg/appregistry/input.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/command.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/imagereader.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/empty.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/image.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/CODE-OF-CONDUCT.md
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/GOVERNANCE.md
  vendor/google.golang.org/grpc/MAINTAINERS.md
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL
