Repository openshift/oc, pull requests merged in 2020-06, with the labels that each got.

#442 adm/release/info: add `--list-bugs` flag
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#433 Bug 1774616: Update BuildLogOptions
  go.mod
  go.sum
  pkg/cli/logs/logs.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#443 Fix flag name in the error when invoking oc adm release info
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#445 Bug 1842582: Don't include digest in source for ICSP when mirroring a catalog
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#446 Bug 1806780: release: Mirroring from custom directory via oc adm release mirror fails
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#322 Add since-second and since-time feature so that pod
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, size/S

#440 Bug 1841005: fix new-app help to mention deployment and/or dc
  pkg/cli/kubectlwrappers/wrappers.go
  pkg/cli/newapp/newapp.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#454 Bug 1629524: only print/update changed rolebindings when removing roles
  pkg/cli/admin/policy/modify_roles.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#444 bug 1840411: oc project: respect --context flag
  pkg/cli/project/project.go
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#448 add complete event json to inspect and must-gather results
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/port_forward.go
  pkg/cli/admin/inspect/util.go
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm

#453 Bug 1843929: use wrapper for kustomize sub-command
  pkg/cli/cli.go
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#435 Bug 1827486: clarify usage of 'oc adm create-kubeconfig'
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/createkubeconfig/create_kubeconfig.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#459 bug 1844354: oc set probe: add support for startup probe
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/set/probe.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#469 bug 1840411: oc project: rewrite context after kubeconfig is read
  pkg/cli/project/project.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#468 Bug 1846078: fix typo in oc adm upgrade help
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#463 Bug 1817145: Improve 'oc adm release info|new' error when given release image does not exist
  pkg/cli/image/extract/extract.go
  pkg/cli/image/info/info.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#464 Write a proper readme
  README.md
Labels: approved, lgtm

#476 Bug 1849983: allow switching project even to users outside self-provisioner role (revert)
  pkg/cli/login/loginoptions.go
  pkg/cli/project/project.go
  pkg/helpers/describe/projectstatus.go
  pkg/helpers/errors/login.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#467 oc adm release extract - add option to extract credential requests only
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#428 [release-4.4] Bug 1808174: bump(golang.org/x/crypto|net|sys)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#449 make oc adm inspect run in parallel and remove rate limits
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm
