Repository openshift/oc, pull requests merged in 2020-08, with the labels that each got.

#509 Bug 1861559: Only schedule must-gather pod on Linux nodes
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#485 Add option to generate ImageContentSourcePolicy scoped to a registry
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
Labels: approved, lgtm

#515 inspect: add back related object (involvedObject) column
  pkg/cli/admin/inspect/event_filter_html.go
Labels: approved, lgtm

#511 Bug 1866597: use a fips compliant, but officially supported OCP template, with new-project message
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#519 Bug 1859452: Improve help menu when 'oc image mirror' and multi-arch images
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#521 Bug 1868324: oc logout should make the token invalid
  pkg/cli/logout/logout.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#526 Bug 1866876: Signature verify error msgs to klog.V(4) rather than klog.Infof
  pkg/helpers/release/verify.go
Labels: approved, bugzilla/valid-bug, lgtm

#522 Bug 1867594: Clarify which registry/repository fails with unauthorized
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#520 Bug 1867792: Allow prune to move on with Removed registry
  pkg/cli/admin/prune/images/images.go
  pkg/cli/admin/prune/images/images_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#518 Bug 1866380: must-gather ImagePullPolicy should be 'Always'
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#528 pkg/cli/admin/release: Delegate to update-approvers
  pkg/cli/admin/release/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#527 Bug 1866399: Shorten retry interval in must-gather
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#536 Bug 1873275: Use echoserver as simple k8s application
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#530 Bug 1872709: Copy foreign layers from external sources during mirroring
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/mirror/plan.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
