Repository openshift/oc, pull requests merged in 2020-01, with the labels that each got.

#236 Respect -mod=vendor for go list
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/modules.txt
Labels: approved, lgtm, size/S

#222 Bug 1785194: don't gather pod endpoints using tokens
  pkg/cli/admin/inspect/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#232 Remove deprecated buildlogs command
  pkg/cli/buildlogs/buildlogs.go
  pkg/cli/cli.go
Labels: approved, lgtm, size/L

#241 Bug 1788088: When "oc status" run, "panic: runtime error: invalid memory address or nil pointer dereference" is shown
  pkg/helpers/describe/projectstatus.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#234 Bug 1778019: If required flag is not passed, don't print usage menu, only print error
  go.mod
  go.sum
  pkg/helpers/cmd/templater.go
  vendor/k8s.io/kubectl/pkg/util/templates/templater.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#240 Verify imports
  Makefile
  hack/verify-imports.sh
  tools/genman/gen_man.go
Labels: approved, lgtm, size/M

#231 Bug 1774424: set builder flags so it prints resources when nothing is specified
  pkg/cli/set/imagelookup.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#246 Bug 1788194: allow --config and --kubeconfig
  go.mod
  go.sum
  pkg/cli/kubectlwrappers/wrappers.go
  vendor/k8s.io/kubectl/pkg/cmd/config/config.go
  vendor/k8s.io/kubernetes/cmd/genutils/BUILD
  vendor/k8s.io/kubernetes/cmd/genutils/genutils.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#230 Set path based on requestURI, not just path
  pkg/cli/set/probe.go
Labels: approved, lgtm, size/XS

#245 Fixes wrong placement of waitgroup.Add function
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, size/XS

#250 Bug 1779519: fix version ldflags
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#254 Bug: 1773266: UPSTREAM: 85490 don't error if set-resources|subject patch empty
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/set/set_resources.go
  vendor/k8s.io/kubectl/pkg/cmd/set/set_subject.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#257 Bug 1790978: Zeroing BearerTokenFile for prune.
  pkg/cli/admin/prune/images/images.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#262 Bug 1792330: pods that are no longer running can still have logs
  pkg/cli/admin/inspect/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#259 Bug 1762837: Restrict pings to remote registry prior to prune.
  pkg/cli/admin/prune/images/images.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#261 Bug 1792330: collect endpoints for namespaces
  pkg/cli/admin/inspect/namespace.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#256 Deprecate --config flag
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  go.mod
  go.sum
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/patch_config_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/config/config.go
  vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#252 Bug 1790802: Pass security options for `oc adm catalog mirror`
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#253 Bug 1790798: Mirror images one by one for oc adm catalog mirror
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#274 Bug 1796182: remove destination digests if present
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#260 Bug 1794606: Use polymorphic helpers from exec, when reading a pod
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/rsh/rsh.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
