Repository openshift/oc, pull requests merged in 2020-07, with the labels that each got.

#480 Bug 1851817: fix filter-by-os parsing for oc adm catalog mirror
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#479 Bug 1845766: Add status to ErrNotV2Registry
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#484 bug 1829243: Revert "run inspect in parallel"
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#478 Bug 1854388: Revert interval and timeout in mustgather so they make sense
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#487 inspect: improve the event filter page
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/inspect/eventFilterPage.go
  pkg/cli/admin/inspect/event_filter_html.go
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm

#429 [release-4.3] Bug 1808221: bump(golang.org/x/crypto|net|sys)
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#458 Bug 1806782: Allow a file:// release argument to release mirror
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#475 Replace custom printing with built-in printing in obseve commad
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/observe/metric.go
  pkg/cli/observe/observe.go
  pkg/cli/observe/printer.go
  pkg/cli/observe/store.go
Labels: approved, lgtm

#492 extract: Make destination paths to absolute to avoid symlink errors
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm

#493 Bug 1850931: 'oc image mirror' Add warning when mirroring SchemaVersion:1 images
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/mirror/plan.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#460 Bug 1844998: Fix --save-config for kubectl create commands, where it was missing
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/create/build.go
  pkg/cli/create/clusterquota.go
  pkg/cli/create/create.go
  pkg/cli/create/deploymentconfig.go
  pkg/cli/create/identity.go
  pkg/cli/create/imagestream.go
  pkg/cli/create/imagestreamtag.go
  pkg/cli/create/route.go
  pkg/cli/create/routeedge.go
  pkg/cli/create/routepassthrough.go
  pkg/cli/create/routereenecrypt.go
  pkg/cli/create/user.go
  pkg/cli/create/user_identity_mapping.go
  pkg/cli/debug/debug.go
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#497 inspect: improve html event viewer
  pkg/cli/admin/inspect/event_filter_html.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm

#501 bump(k8s.io/kubectl) for CSR fix
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/certificates/certificates.go
  vendor/modules.txt
Labels: approved, lgtm

#502 debug: fix dry-run flag parsing
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#503 create: fix create useridentitymapping
  pkg/cli/create/create.go
  pkg/cli/create/user_identity_mapping.go
Labels: approved, lgtm

#505 prune images: expose the number of workers as a flag
  .gitignore
  README.md
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/prune/images/images.go
Labels: approved, lgtm

#495 release: Hide empty metadata fields in release info
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#500 Prepare for RHEL 8
  images/tools/Dockerfile
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#508 pkg/cli/adm/catalog: Delegate to catalog-approvers
  OWNERS_ALIASES
  pkg/cli/admin/catalog/OWNERS
Labels: approved, lgtm
