Repository openshift/oc, pull requests merged in 2020-10, with the labels that each got.

#551 Bug 1860789: Rebase k8s to 1.18.8 to enable approving CSRs on a 4.6 server
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kubectl/pkg/cmd/certificates/certificates.go
  vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go
  vendor/k8s.io/kubectl/pkg/describe/describe.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#558 cli/admin/release/new: typo fix
  pkg/cli/admin/release/new.go
Labels: approved, lgtm

#481 must-gather: fixed typo when using a plug-in image
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, ok-to-test

#534 Refactor deletion of hashed session token on user logout
  pkg/cli/logout/logout.go
Labels: approved, lgtm

#596 Bug 1878163: Updating openshift-enterprise-cli builder & base images to be consistent with ART
  images/cli/Dockerfile.rhel
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#603 Bug 1885170: fix nil pointer in release code
  go.mod
  go.sum
  pkg/cli/admin/release/mirror.go
  pkg/helpers/release/configmap.go
  pkg/helpers/release/verify.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/library-go/pkg/verify/configmap.go
  vendor/github.com/openshift/library-go/pkg/verify/store/serial/serial.go
  vendor/github.com/openshift/library-go/pkg/verify/verify.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#605 Bug 1885959: fix nil pointer in release code
  go.mod
  go.sum
  pkg/cli/admin/release/mirror.go
  pkg/helpers/release/configmap.go
  pkg/helpers/release/verify.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/library-go/pkg/verify/configmap.go
  vendor/github.com/openshift/library-go/pkg/verify/store/serial/serial.go
  vendor/github.com/openshift/library-go/pkg/verify/verify.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#610 Bug 1884270: bypass golang url parsing with scp styled ssh git URLs; refactor URL for older git clients
  pkg/helpers/source-to-image/git/url.go
  pkg/helpers/source-to-image/git/url_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#612 release: Fix typo in cli argument for release mirror
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm

#553 oc login: Show tokenURL message if only IDP is basic and user has not provided username
  pkg/cli/login/login.go
  pkg/helpers/tokencmd/basicauth.go
  pkg/helpers/tokencmd/basicauth_test.go
  pkg/helpers/tokencmd/request_token.go
  pkg/helpers/tokencmd/request_token_test.go
Labels: approved, lgtm

#604 Bug 1885179: Avoid deadlock by closing pipe reader end
  pkg/helpers/image/dockerlayer/add/add.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#602 [release-4.5] Bug 1884580: Set appropriate owner references when creating a job from cronjob
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#537 Bug 1868384: Login: Avoid overwriting same user from different cluster
  pkg/helpers/kubeconfig/smart_merge.go
  pkg/helpers/originkubeconfignames/smart_merge.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#609 Updating ose-cli-artifacts builder & base images to be consistent with ART
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm

#608 Updating openshift-enterprise-deployer builder & base images to be consistent with ART
  images/deployer/Dockerfile.rhel
Labels: approved, lgtm

#606 Updating openshift-enterprise-cli builder & base images to be consistent with ART
  images/cli/Dockerfile.rhel
Labels: approved, lgtm

#607 Updating ose-tools builder & base images to be consistent with ART
  images/tools/Dockerfile
Labels: approved, lgtm

#611 Bug 1841885: Support airgapped mirroring with `oc adm catalog mirror`
  go.mod
  go.sum
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
  pkg/cli/admin/catalog/mirrorer.go
  pkg/cli/admin/catalog/mirrorer_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#597 Bug 1878163: Updating ose-cli-artifacts builder & base images to be consistent with ART
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#616 Bug 1888657: set command name for LoginOptions
  pkg/cli/login/loginoptions.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#623 Bug 1891555: Create Windows version information
  Makefile
  hack/generate-versioninfo.sh
Labels: approved, lgtm

#622 fix help for 'oc adm release extract'
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#601 [release-4.4] Bug 1884569: Set appropriate owner references when creating a job from cronjob
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#482 Bug 1853116: write to files instead of stdout
  pkg/cli/admin/release/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#625 show proper wildcard for 'oc image mirror --help example'
  pkg/cli/image/mirror/mirror.go
Labels: approved, lgtm

#627 Bug 1888738: fall-back must-gather to official RH supported image
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#629 Bug 1891555: BuildRequires goversioninfo
  oc.spec
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
