Repository openshift/oc, pull requests merged in 2020-05, with the labels that each got.

#389 Bug 1826533: pkg/cli/admin/upgrade: Warn when --allow-upgrade-with-warnings let you through
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#390 Bug 1826533: pkg/cli/admin/upgrade: Client-side by-tag guard
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#409 Bug 1826230: bring missing fixes to oc
  go.mod
  go.sum
  pkg/cli/shim_kubectl.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/patch_config_flags.go
  vendor/k8s.io/client-go/tools/clientcmd/validation.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#405 Bug 1802719: oc adm groups sync IsQueryOutOfBoundsError warning,not error
  pkg/helpers/groupsync/groupsyncer.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#413 bug 1826676: oc status: check if the current project exists before printing status
  pkg/cli/project/project.go
  pkg/cli/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#407 Bug 1780447: replace kubectl with oc in oc rollout restart help
  pkg/cli/rollout/rollout.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#421 Bug 1835997: create route reencrypt: Improve --dest-ca-cert help
  pkg/cli/create/routereenecrypt.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#414 Bug 1827073: Support mirroring catalogs using default-tagged source images.
  pkg/cli/admin/catalog/mirrorer.go
  pkg/cli/admin/catalog/mirrorer_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#422 bug 1827463: oc sa create-kubeconfig: respect --context flag
  pkg/cli/serviceaccounts/create_kubeconfig.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#424 Bug 1806779: Mirroring from custom directory via oc adm release mirror fails
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#355 Bug 1836833: Switch new-app to generate deployment, by default
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/newapp/newapp.go
  pkg/helpers/newapp/app/app.go
  pkg/helpers/newapp/app/imageref.go
  pkg/helpers/newapp/app/imageref_test.go
  pkg/helpers/newapp/app/pipeline.go
  pkg/helpers/newapp/appjson/appjson.go
  pkg/helpers/newapp/cmd/describe.go
  pkg/helpers/newapp/cmd/newapp.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#431 Bug 1835011: improve error for 'oc project' and 'oc status' when project doesn't exist
  pkg/cli/project/project.go
  pkg/cli/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#430 Bug 1837375: use http.Client.Head instead of tls.Dial to be able to consume proxy settings
  pkg/helpers/tokencmd/request_token.go
  pkg/helpers/tokencmd/request_token_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#397 Bug 1801292: support -f for rsh command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/rsh/rsh.go
  pkg/cli/rsync/copy_rsync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#406 Bug 1802580: return ProjectRequestMessage if it is set with login,project cmds
  pkg/cli/login/loginoptions.go
  pkg/cli/project/project.go
  pkg/helpers/describe/projectstatus.go
  pkg/helpers/errors/login.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#432 bug 1838614: Backport oc status project 4.5 changes
  pkg/cli/project/project.go
  pkg/cli/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#434 Bug 1838838: oc adm group sync - search outside base dn warning - RFC 2307
  pkg/helpers/groupsync/rfc2307/ldapinterface.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#436 Bug 1839631: fix validation code for arguments passed
  pkg/cli/rsh/rsh.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#437 Bug 1838934: Fix new-app producing deployment that trigger twice after creation
  pkg/cli/newapp/newapp.go
  pkg/helpers/newapp/app/app.go
  pkg/helpers/newapp/cmd/newapp.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#438 Bug 1829832: support mirroring for index images
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#412 Bug 1833558: create ClusteRole and ClusterRoleBinding when invoking oc adm policy add-scc-to-user
  pkg/cli/admin/policy/authz_helpers.go
  pkg/cli/admin/policy/modify_roles.go
  pkg/cli/admin/policy/modify_scc.go
  pkg/cli/admin/policy/modify_scc_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#420 [release-4.4] Bug 1835739: Fix oc drain to ignore daemonsets and others
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#423 Bug 1827544: provide better defaults for oc adm catalog build
  pkg/cli/admin/admin.go
  pkg/cli/admin/catalog/build.go
  pkg/cli/admin/catalog/catalog.go
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#426 Bug 1837675: Backport enhancements/oc/mirroring-release-signatures implementation
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  go.mod
  go.sum
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/helpers/release/configmap.go
  pkg/helpers/release/configmap_test.go
  pkg/helpers/release/testdata/keyrings/combined.txt
  pkg/helpers/release/testdata/keyrings/redhat.txt
  pkg/helpers/release/testdata/keyrings/simple.txt
  pkg/helpers/release/testdata/signatures-2/.gitkeep
  pkg/helpers/release/testdata/signatures/sha256=e3f12513a4b22a2d7c0e7c9207f52128113758d9d68c7d06b11a0ac7672966f7/signature-1
  pkg/helpers/release/testdata/signatures/sha256=edd9824f0404f1a139688017e7001370e2f3fbc088b94da84506653b473fe140/signature-1
  pkg/helpers/release/verify.go
  pkg/helpers/release/verify_test.go
  vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor/descriptor.pb.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
