Repository openshift/oc, pull requests merged in 2020-03, with the labels that each got.

#339 Bug 1810256: Don't default to always mirror manifestlists
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#340 Bug 1810310: fix examples in help
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#307 Bug 1802881: bump(github.com/mtrmac/gpgme): v0.1.2
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#345 release: Changelog fails when new image added
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, size/XS

#106 oc.spec: Update to Go 1.13 and make it consumable by 3rd party build services
  oc.spec
Labels: approved, lgtm, size/S

#346 oc debug: add help for --to-namespace
  pkg/cli/debug/debug.go
Labels: approved, lgtm, size/XS

#332 `set volume` does not work with `--local`
  pkg/cli/set/helper.go
  pkg/cli/set/volume.go
Labels: approved, lgtm, size/M

#242 Add --exclude flag to start-build
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/startbuild/startbuild.go
  pkg/cli/startbuild/startbuild_test.go
Labels: approved, lgtm, ok-to-test, size/M

#350 Fix oc rsync help
  pkg/cli/rsync/rsync.go
Labels: approved, lgtm

#337 Place apache license in cli-artifacts
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, ok-to-test, size/XS

#334 Bug 1809028: replace kubectl with oc in wait's help
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#353 images: Add a tools image for use with debug and system administration
  images/tools/Dockerfile
  images/tools/OWNERS
Labels: approved, lgtm

#317 Use relative symlinks for disk mirroring
  pkg/cli/image/imagesource/file.go
Labels: approved, lgtm, ok-to-test, size/XS

#347 Fix a number of bugs in debug
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/debug/debug.go
  pkg/helpers/conditions/conditions.go
Labels: approved, lgtm

#357 images/tools: Remove numactl* packages until they are available on s390x
  images/tools/Dockerfile
Labels: approved, lgtm

#294 Bug 1802262: Use polymorphic helpers from exec, when reading a pod
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/rsh/rsh.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#360 images/tools: Don't change user
  images/tools/Dockerfile
Labels: approved, lgtm

#358 release: Perform release extract in parallel
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/git.go
Labels: approved, lgtm

#364 release: In markdown output, only < and > are unsafe characters
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#255 Bug 1790954: fix version ldflags
  Makefile
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#349 Remove dead code
  pkg/cli/set/volume.go
Labels: approved, lgtm
