Repository openshift/oc, pull requests merged in 2021-09, with the labels that each got.

#906 Bug 1994872: Fix manifest path regression
  pkg/cli/image/imagesource/file.go
  pkg/cli/image/imagesource/file_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#908 Bug 1996881: adm catalog mirror: log deprecation message when sqlite-based catalog is in use
  pkg/cli/admin/catalog/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#907 Bug 1990014: Use cmd for Windows pods
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#903 Bug 1992680: pkg/cli/admin/upgrade: Changing "Updates" string to "Available Updates"
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#921 Add kevinrizza as catalog-approver
  OWNERS_ALIASES
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved

#892 [release-4.6] Bug 1942818: when mirroring to a file destination, mount images under the index location
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirrorer.go
  pkg/cli/admin/catalog/mirrorer_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#925 Bug 2002950: Define a Command instead of Arguments for Container
  pkg/cli/create/deploymentconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#926 Bug 2004193: Registry mirror panic
  pkg/cli/admin/catalog/mirrorer.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved

#919 Bug 1977414: check BuildConfig Secrets and ConfigMaps before start-build creates a build
  pkg/cli/startbuild/startbuild.go
  pkg/cli/startbuild/startbuild_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#927 Bug 2004194: Registry mirror panic
  pkg/cli/admin/catalog/mirrorer.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#936 Add MacOS local building instructions to README
  README.md
Labels: approved, lgtm

#943 Drop policy mentions in oc adm policy help
  pkg/cli/admin/policy/policy.go
Labels: approved, lgtm
