Repository openshift/oc, pull requests merged in 2021-11, with the labels that each got.

#566 Bug 1878925: pkg/cli/admin/upgrade: Remove help text around history lookups
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, lifecycle/rotten, bugzilla/valid-bug, bugzilla/severity-low

#812 Bug 1952230: pkg/cli/admin/upgrade: Always run all client-side checks
  pkg/cli/admin/upgrade/upgrade.go
  pkg/cli/admin/upgrade/upgrade_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#952 pkg/cli/admin/upgrade: Indent multi-line messages
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#967 GitHub-38217: Removing old example that mentions limitSecretReferences
  pkg/cli/secrets/link.go
Labels: approved, lgtm

#961 Display conditional and not-recommended versions
  contrib/completions/bash/oc
  pkg/cli/admin/upgrade/upgrade.go
  pkg/cli/admin/upgrade/upgrade_test.go
Labels: approved, lgtm

#965 mustgather: add NodeName to destDir folder name
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm

#976 Drop patches for apimachinery and client-go forks
  go.mod
  go.sum
  pkg/cli/admin/prune/auth/group_test.go
  pkg/cli/admin/prune/auth/user_test.go
  pkg/cli/shim_kubectl.go
  vendor/k8s.io/apimachinery/pkg/api/meta/restmapper.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/component-base/metrics/options.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm

#973 Fix docs for oc adm policy add-role-to-user vs oc policy add-role-to-user
  pkg/cli/admin/policy/modify_roles.go
  pkg/cli/admin/policy/policy.go
  pkg/cli/admin/policy/remove_from_project.go
  pkg/cli/admin/policy/review.go
  pkg/cli/admin/policy/subject_review.go
  pkg/cli/policy/policy.go
Labels: approved, lgtm

#962 Bug 2020377: add linux capability for host network packet captures
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#977 Adding an example for oc adm upgrade
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#893 Bug 1982498: default to podman credential configs
  go.mod
  pkg/cli/image/manifest/dockercredentials/auth_resolver.go
  pkg/cli/image/manifest/dockercredentials/auth_resolver_test.go
  pkg/cli/image/manifest/dockercredentials/credential_store_factory_test.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
  vendor/github.com/BurntSushi/toml/.gitignore
  vendor/github.com/BurntSushi/toml/.travis.yml
  vendor/github.com/BurntSushi/toml/COMPATIBLE
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/Makefile
  vendor/github.com/BurntSushi/toml/README.md
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/encoding_types.go
  vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/session.vim
  vendor/github.com/BurntSushi/toml/type_check.go
  vendor/github.com/BurntSushi/toml/type_fields.go
  vendor/github.com/containers/image/v5/internal/pkg/keyctl/key.go
  vendor/github.com/containers/image/v5/internal/pkg/keyctl/keyring.go
  vendor/github.com/containers/image/v5/internal/pkg/keyctl/perm.go
  vendor/github.com/containers/image/v5/internal/pkg/keyctl/sys_linux.go
  vendor/github.com/containers/image/v5/internal/rootless/rootless.go
  vendor/github.com/containers/image/v5/pkg/docker/config/config.go
  vendor/github.com/containers/image/v5/pkg/docker/config/config_linux.go
  vendor/github.com/containers/image/v5/pkg/docker/config/config_unsupported.go
  vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
  vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go
  vendor/github.com/containers/storage/pkg/lockfile/lockfile.go
  vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go
  vendor/github.com/containers/storage/pkg/lockfile/lockfile_windows.go
  vendor/github.com/containers/storage/pkg/stringid/README.md
  vendor/github.com/containers/storage/pkg/stringid/stringid.go
  vendor/github.com/docker/docker-credential-helpers/LICENSE
  vendor/github.com/docker/docker-credential-helpers/client/client.go
  vendor/github.com/docker/docker-credential-helpers/client/command.go
  vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
  vendor/github.com/docker/docker-credential-helpers/credentials/error.go
  vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved
