Repository openshift/oc, pull requests merged in 2021-10, with the labels that each got.

#935 Bug 1926522: oc adm catalog mirror tmp directory cleanup
  pkg/cli/admin/catalog/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#880 runAsNonRoot in Pod SCC should be nil when oc debug run with `--as-root`
  pkg/cli/debug/debug.go
Labels: approved, ok-to-test, lgtm

#850 [must-gather] Add options for multi-node / host-network capture
  contrib/completions/bash/oc
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, tide/merge-method-squash, lgtm

#881 Make sure to set the namespace for routes resources
  pkg/cli/create/route/route.go
  pkg/cli/create/routeedge.go
  pkg/cli/create/routepassthrough.go
  pkg/cli/create/routereenecrypt.go
  pkg/cli/expose/expose.go
Labels: approved, tide/merge-method-squash, ok-to-test, lgtm
