Repository openshift/oc, pull requests merged in 2021-04, with the labels that each got.

#788 Fix usage error print
  pkg/cli/process/process.go
Labels: approved, lgtm

#798 Updating generate docs output for product docs
  hack/clibyexample/template
  tools/gendocs/gen_openshift_docs.go
  tools/gendocs/gendocs/gendocs.go
Labels: approved, lgtm

#801 OSDOCS-2033: Adding examples for some CLI commands
  pkg/cli/admin/createbootstrapprojecttemplate/create_bootstrap_project_template.go
  pkg/cli/admin/createerrortemplate/create_error_template.go
  pkg/cli/admin/createlogintemplate/create_login_template.go
  pkg/cli/admin/createproviderselectiontemplate/create_provider_selection_template.go
  pkg/cli/admin/project/new_project.go
  pkg/cli/projects/projects.go
  pkg/cli/whoami/whoami.go
Labels: approved, lgtm

#780 Bug 1946839: Revert: Split work of oc image mirror
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/image/mirror/mappings.go
  pkg/cli/image/mirror/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#768 Bug 1925148: ImageRef Stream name priority increased
  pkg/helpers/newapp/app/imageref.go
  pkg/helpers/newapp/app/imageref_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#805 Bug 1890828: Skip images that has already been deleted
  pkg/cli/admin/prune/imageprune/prune.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#766 bug 1942938: [release-4.7] inspect clusteroperators as a backup to must-gather if it fails
  go.sum
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/inspect_test.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/route.go
  pkg/cli/admin/inspect/secret.go
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/summary.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#726 Remove tnozicka from OWNERS and clean those files too
  OWNERS
  OWNERS_ALIASES
  images/tools/OWNERS
  pkg/cli/admin/prune/imageprune/OWNERS
  pkg/cli/cancelbuild/OWNERS
  pkg/cli/deployer/OWNERS
  pkg/cli/newapp/OWNERS
  pkg/cli/newbuild/OWNERS
  pkg/cli/startbuild/OWNERS
  pkg/helpers/bulk/OWNERS
  pkg/helpers/newapp/OWNERS
  pkg/helpers/originpolymorphichelpers/deploymentconfigs/OWNERS
  tools/clicheck/OWNERS
  tools/gendocs/OWNERS
  tools/genman/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#797 Bug 1937020: `oc adm release new` should look at image stream status tags
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#782 bug 1942940: [release-4.6] inspect clusteroperators as a backup to must-gather if it fails
  go.sum
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/inspect_test.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/route.go
  pkg/cli/admin/inspect/secret.go
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/summary.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#810 Bug 1949820: Add an alias to imagestreams in top command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/top/imagestreams.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#771 Add stress and fio packages to tools image
  images/tools/Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#815 Bug 1937020: Releases from image streams must prefer status tag
  pkg/cli/admin/release/new.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#808 Bug 1947430: Revert "Bug 1812813: oc debug node: create debug namespace"
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved
