Repository openshift/oc, pull requests merged in 2021-06, with the labels that each got.

#814 Bug 1953563: Makefile: add verify-golang-versions
  Makefile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#838 [release-4.7] Fix unit test failure
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#759 Bug 1936904: Insert apiVersion and Kind into `oc adm groups sync` list output
  pkg/cli/admin/groups/sync/sync.go
  pkg/helpers/groupsync/groupsyncer.go
  pkg/helpers/groupsync/groupsyncer_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#834 Bug 1893999: guide user to provide username with basic auth error/only password IDP and no username provided
  pkg/helpers/tokencmd/basicauth.go
  pkg/helpers/tokencmd/request_token.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#835 Bug 1965330: exclude security during exctraction
  pkg/cli/image/archive/archive.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#841 Bug 1968515: set User-Agent when talking with registries
  pkg/cli/admin/verifyimagesignature/manifest.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/info/info.go
  pkg/cli/registry/login/login.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#818 Bug 1951203: Allow users to set a limit on ICSP file size
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  go.mod
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#840 Bug 1954124: deprecate storage-class annotation in favor of spec.StorageClassName
  pkg/cli/set/volume.go
  pkg/cli/set/volume_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#839 [release-4.6] Fix unit test failure
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#747 Add json.Valid check before trying to read docker config
  pkg/helpers/image/credentialprovider/config.go
Labels: approved, lgtm

#860 Update ruby-hello-world images
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm

#863 Bug 1973643: make oc logs work with BuildConfig's JenkinsPipeline strategy
  pkg/cli/logs/logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#739 fix typo in examples template
  pkg/cli/set/probe.go
Labels: approved, lgtm, lifecycle/stale, ok-to-test

#861 [release-4.7] Bug 1963784: Preserve AuthInfo when switching projects
  pkg/helpers/kubeconfig/smart_merge.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#869 [release-4.7] Bug 1976284: skip-multiple-scopes with adm catalog mirror
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#751 Bug 1925534: Add proxy to oc
  pkg/helpers/kubeconfig/smart_merge.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#816 release: extract Linux binaries for multiple architectures
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm

#862 [release-4.6] Bug 1973613: Preserve AuthInfo when switching projects
  pkg/helpers/kubeconfig/smart_merge.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
