Repository openshift/oc, pull requests merged in 2021-01, with the labels that each got.

#676 Bug 1909289: Should be able to debug an init container
  pkg/cli/debug/debug.go
  pkg/helpers/conditions/conditions.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#671 Bug 1880068: Take StatefulSets, Jobs and CronJobs into account during image prune
  pkg/cli/admin/prune/imageprune/prune.go
  pkg/cli/admin/prune/imageprune/prune_test.go
  pkg/cli/admin/prune/images/images.go
  pkg/helpers/image/test/util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#684 Bug 1910840: fix help for rollback
  pkg/cli/rollback/rollback.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#687 Bug 1908484: credentials-requests extract only write creds requests not all manifests
  pkg/cli/admin/release/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#688 Bug 1914452: Fix the manifest list warning when choosing an os/arch digest from list
  pkg/cli/image/manifest/manifest.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#682 Bug 1908697: use wrapper for diff command
  pkg/cli/cli.go
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#683 Bug 1911487: make deployment config explicit for prune deployments
  pkg/cli/admin/prune/deployments/deployments.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#691 Bug 1890995: oc new-app: provide message for unauthorized error with image lookup
  pkg/helpers/newapp/app/dockerimagelookup.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#696 Bug 1899575: bump discovery burst to 250
  pkg/cli/cli.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#697 Bug 1890677: oc image: Include error msg when image not found and register oci schema for mediatypes
  pkg/cli/image/extract/extract.go
  pkg/cli/image/info/info.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/image/mirror/mirror.go
  vendor/github.com/docker/distribution/manifest/ocischema/builder.go
  vendor/github.com/docker/distribution/manifest/ocischema/manifest.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#707 Bug 1906276: oc image append|extract: clarify help for --filter-by-os
  pkg/cli/image/append/append.go
  pkg/cli/image/extract/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#708 Bug 1916621: fix oc adm node-logs examples
  pkg/cli/admin/node/logs.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#673 Bug 1902299: catalog mirror improvements
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_options.go
  pkg/cli/admin/catalog/mirrorer.go
  pkg/cli/admin/catalog/mirrorer_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#710 Bug 1917522: Mark filter-by-os deprecated in oc adm catalog mirror
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/mirror.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#716 [release-4.6] Bug 1906332: bump discovery burst to 250
  go.mod
  go.sum
  pkg/cli/cli.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#711 Bug 1917548: 4.6 backports for oc adm catalog mirror
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/catalog/internal/parse.go
  pkg/cli/admin/catalog/internal/parse_test.go
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_options.go
  pkg/cli/admin/catalog/mirror_test.go
  pkg/cli/admin/catalog/mirrorer.go
  pkg/cli/admin/catalog/mirrorer_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#712 Bug 1878022: Improving import-image help messages
  pkg/cli/importimage/importimage.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#717 Bug 1920427: drop information about prompt for oc login
  pkg/cli/login/login.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#630 [release-4.6] Bug 1891892: Create Windows version information
  Makefile
  hack/generate-versioninfo.sh
  oc.spec
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
