Repository openshift/oc, pull requests merged in 2021-07, with the labels that each got.

#872 [release-4.6] Bug 1971561: set User-Agent when talking with registries
  pkg/cli/admin/verifyimagesignature/manifest.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/info/info.go
  pkg/cli/registry/login/login.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#876 Bug 1976112: Fixed warnings about deprecated CronJob in image-pruner pods
  pkg/cli/admin/prune/imageprune/prune.go
  pkg/cli/admin/prune/imageprune/prune_test.go
  pkg/cli/admin/prune/images/images.go
  pkg/helpers/image/test/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#576 pkg/cli/admin/upgrade/channel: Add 'oc adm upgrade channel ...'
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/admin/upgrade/channel/channel.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#878 contrib/completions/OWNERS: Delegate to all approver aliases
  OWNERS
  OWNERS_ALIASES
  contrib/completions/OWNERS
Labels: approved, lgtm

#877 [release-4.6] Bug 1969929: exclude security during exctraction
  pkg/cli/image/archive/archive.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#882 Bug 1955292: show consistent unit format in cluster resource quota describe
  pkg/helpers/describe/describer.go
  pkg/helpers/describe/describer_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#874 Bug 1978629: Add oc describe output for build volumes
  .gitignore
  pkg/helpers/describe/describer.go
  pkg/helpers/describe/describer_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved

#887 Bug 1980118: Keep workload annotations during the `oc debug` call.
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#852 Support ibmcloud provider in release extract
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#875 Bug 1971332: revert incorrect allowance of ssh:// prefix with scp styled URLs
  pkg/helpers/newapp/cmd/newapp_test.go
  pkg/helpers/source-to-image/git/url.go
  pkg/helpers/source-to-image/git/url_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
