Repository openshift/oc, pull requests merged in 2021-08, with the labels that each got.

#867 [release-4.8] Bug 1974267: make oc logs work with BuildConfig's JenkinsPipeline strategy
  pkg/cli/logs/logs.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#897 Bug 1903545: Replace colons with dashes in Windows file paths
  pkg/cli/image/imagesource/file.go
  pkg/cli/image/imagesource/file_unix.go
  pkg/cli/image/imagesource/file_windows.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#894 Bug 1786835: Check for out of range condition
  pkg/cli/admin/catalog/mirrorer.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#899 Bug 1992680: pkg/cli/admin/upgrade/upgrade: Copy edits, including "assists with cluster upgrades"
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#895 Bug 1989391: Revert to UnstructuredList to fix yaml output
  pkg/cli/admin/groups/sync/sync.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#905 Bug 1995573: Replacing kubectl with oc adm in help for certificate ap…
  pkg/cli/admin/admin.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#767 Bug 1995291: Remove docker adjective whenever possible.
  contrib/completions/bash/oc
  pkg/cli/admin/migrate/images/imagerefs.go
  pkg/cli/importimage/importimage.go
  pkg/cli/newapp/newapp.go
  pkg/cli/newapp/newapp_test.go
  pkg/cli/newbuild/newbuild.go
  pkg/cli/newbuild/newbuild_test.go
  pkg/helpers/image/credentialprovider/keyring.go
  pkg/helpers/newapp/app/dockerimagelookup.go
  pkg/helpers/newapp/app/imagestreamlookup_test.go
  pkg/helpers/newapp/appjson/appjson.go
  pkg/helpers/newapp/cmd/newapp.go
  pkg/helpers/newapp/cmd/resolve.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#910 Bug 1999159: Update the catalog-related owner alias'
  OWNERS_ALIASES
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#909 Bug 1989505: bump kubernetes-client-go library
  go.mod
  go.sum
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#891 Bug 1989504: The code logic of channel clear is ambiguous, as well as the help info and output messages
  pkg/cli/admin/upgrade/channel/channel.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
