Repository openshift/oc, pull requests merged in 2021-12, with the labels that each got.

#983 fix registry-config messages and imports
  pkg/cli/image/manifest/dockercredentials/auth_resolver.go
  pkg/cli/image/manifest/dockercredentials/auth_resolver_test.go
  pkg/cli/image/manifest/dockercredentials/credential_store_factory.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm

#978 feat/oc-release-extract-cco: add support for alibabacloud
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#944 Fix documentation issue #937
  README.md
Labels: approved, ok-to-test, lgtm

#987 oc adm prune deployments for ReplicaSets
  contrib/completions/bash/oc
  pkg/cli/admin/prune/deployments/data.go
  pkg/cli/admin/prune/deployments/data_test.go
  pkg/cli/admin/prune/deployments/deployments.go
  pkg/cli/admin/prune/deployments/prune.go
  pkg/cli/admin/prune/deployments/prune_test.go
  pkg/cli/admin/prune/deployments/resolvers.go
  pkg/cli/admin/prune/deployments/resolvers_test.go
Labels: approved, lgtm

#990 Add darwin/arm64 oc
  Makefile
  images/cli-artifacts/Dockerfile.rhel
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm

#1000 release: extract darwin/arm64 openshift-install
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm

#986 Adding the flag --allow-not-recommended to oc adm upgrade
  contrib/completions/bash/oc
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#942 Modified MG pod tolerations
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, ok-to-test, lgtm

#995 Bug 2032111: requestproject: use agnhost serve-hostname
  pkg/cli/requestproject/request_project.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1002 Bug 2033751: pkg/cli/admin/inspect: Fix "ocurred" -> "occurred" typos
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1003 Bug 2033751: Revert "Modified MG pod tolerations"
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1005 Bug 2034889: Fix prune deployment panic
  pkg/cli/admin/prune/deployments/deployments.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
