Repository openshift/oc, pull requests merged in 2021-02, with the labels that each got.

#715 Bug 1919862: fix message after oc new-project
  pkg/cli/requestproject/request_project.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#613 Bug 1920024: debug: Allow pods to keep labels during debugging
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#706 Bug 1907421: Implementing retries during for image mirror
  pkg/cli/image/mirror/mirror.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#631 Bug 1888192: add rsync & log re-tries
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/rsh/rsh.go
  pkg/cli/rsync/copy_rsync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#720 Bug 1900989: idle: also annotate the service
  pkg/cli/idle/idle.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#693 Bug 1914894: warn users about using non-groupified resources
  pkg/cli/shim_kubectl.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#725 Add missing docs generation tools
  Makefile
  docs/generated/.gitignore
  hack/clibyexample/OWNERS
  hack/clibyexample/template
Labels: approved, bugzilla/valid-bug, lgtm

#718 [release-4.5] Bug 1920676: add timestamps marking start and end for must-gather and inspect
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/inspect_test.go
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#713 Bug 1919032: Fix image extract from Root Directory
  pkg/cli/image/extract/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#721 Add help text to 'oc registry login' when using --registry flag
  pkg/cli/registry/login/login.go
Labels: approved, lgtm

#690 add simple debug for image serve
  pkg/cli/image/serve/serve.go
Labels: approved, lgtm, ok-to-test

#731 upate registry.svc.ci->registry.ci
  Makefile
Labels: approved, lgtm

#729 Bug 1904006: update and clarify --dir --from-dir flags with 'oc image'
  pkg/cli/image/append/append.go
  pkg/cli/image/extract/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#724 [release-4.6] Bug 1923054: Fix error in jsonpath when object is empty
  OWNERS
  OWNERS_ALIASES
  go.mod
  go.sum
  images/tools/OWNERS
  pkg/cli/admin/prune/imageprune/OWNERS
  pkg/cli/cancelbuild/OWNERS
  pkg/cli/deployer/OWNERS
  pkg/cli/newapp/OWNERS
  pkg/cli/newbuild/OWNERS
  pkg/cli/startbuild/OWNERS
  pkg/helpers/bulk/OWNERS
  pkg/helpers/newapp/OWNERS
  pkg/helpers/originpolymorphichelpers/deploymentconfigs/OWNERS
  tools/clicheck/OWNERS
  tools/gendocs/OWNERS
  tools/genman/OWNERS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#730 Bug 1925236: RouteDescriber: Filter endpoints on route.Spec.Port
  pkg/helpers/describe/describer.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#399 Bug 1920024: Allow debug to start with a single `--image` argument
  pkg/cli/debug/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#742 Bug 1928850: update new-app help to avoid image references without registry/repository (docker.io throttling related)
  pkg/cli/newapp/newapp.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
