Repository openshift/oc, pull requests merged in 2022-09, with the labels that each got.

#1228 Give a complete oc label command in pod security error message
  pkg/helpers/cmd/errors.go
Labels: approved, lgtm

#1148 Bug 2087679: [inspect] Add EgressQoS to inspect
  pkg/cli/admin/inspect/namespace.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1236 OCPBUGS-852: cli/debug: Create temporary namespace for node debugging
  pkg/cli/debug/debug.go
  pkg/cli/debug/debug_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1231 OCPBUGS-613: oc adm logs: generate proper path for static pods
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1241 OCPBUGS-1638: Increase default value of cache TTL to 6 hours
  go.mod
  go.sum
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1234 Add --overwrite flag into pod security violation error message
  pkg/helpers/cmd/errors.go
Labels: approved, lgtm

#1188 Update login.go
  pkg/cli/login/login.go
Labels: approved, ok-to-test, lgtm
