Repository openshift/oc, pull requests merged in 2022-02, with the labels that each got.

#1041 Bug 2044140: Updated the error message to include the suggestion
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1048 Add TMOUT env to debug node pod
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#1050 Bug 2044140: pkg/cli/admin/upgrade: Fix nextStep option sense
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1038 Bug 2047895: release: handle aarch64/arm64 naming disparity in mirror
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1017 Bug 2038931: properly handle --dry-run=server
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cli/set/buildhook.go
  pkg/cli/set/buildsecret.go
  pkg/cli/set/data.go
  pkg/cli/set/deploymenthook.go
  pkg/cli/set/env.go
  pkg/cli/set/imagelookup.go
  pkg/cli/set/probe.go
  pkg/cli/set/routebackends.go
  pkg/cli/set/triggers.go
  pkg/cli/set/volume.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1053 Bug 2046319: improve error message for debug
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1051 Show managedFields in inspect
  pkg/cli/admin/inspect/inspect.go
Labels: approved, lgtm

#951 Remove unused methods and re-use pre-existing ones where needed
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, lifecycle/rotten

#1004 Comment tolerations used in must-gather
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm

#1062 Bug 2052034: make sure that we check for resorces and files before picking the simplest path
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1063 Bug 2049234: Fix mirroring images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, qe-approved

#1067 Bug 2053218: Fix mirroring images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed

#1068 Bug 2053222: Fix mirroring images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/github.com/openshift/library-go/pkg/security/ldapclient/client.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#1069 Bug 2053223: Fix mirroring images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#1071 Update all images to be consistent with ART
  .ci-operator.yaml
  images/cli-artifacts/Dockerfile.rhel
  images/deployer/Dockerfile.rhel
  images/recycler/Dockerfile.rhel
  images/tools/Dockerfile
Labels: approved, lgtm
