Repository openshift/oc, pull requests merged in 2022-07, with the labels that each got.

#1184 Bug 2100708: Lower chosen platform architecture/OS log level
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1183 Bug 2100702: Use from-release as based image when base digest is invalid
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1186 Bug 2101885: Set completion function for get command
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1185 Bug 2100166: Add new IsManifestList flag into ReleaseInfo struct
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1190 [release-4.9] Bug 2103910: Introduce an option to retrieve the rotated log files for a pod
  go.mod
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/pod.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1191 [release-4.9] Bug 2103913: [must-gather] Add options for multi-node, host-network capture
  contrib/completions/bash/oc
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1194 release: extract ccoctl
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm

#1204 release info bug printing: enable `--skip-bug-check` for `--output=json`
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#1199 Support for identity token
  pkg/cli/image/manifest/dockercredentials/auth_resolver.go
  pkg/cli/image/manifest/dockercredentials/credential_store_factory.go
  pkg/cli/image/manifest/dockercredentials/credential_store_factory_test.go
  pkg/helpers/image/credentialprovider/config.go
  pkg/helpers/image/credentialprovider/config_test.go
Labels: approved, lgtm

#1203 Bug 2105325: Add ManifestListDigest field to release info struct
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
  pkg/cli/image/extract/extract.go
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#1161 Bug 1880865: Avoid TLS cert checking when login with --insecure-skip-tls-verify=true
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1213 Bug 2092731: Change error message to signal passing keep-manifest-list flag
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
