Repository openshift/oc, pull requests merged in 2022-10, with the labels that each got.

#1248 Bug 2033167: oc extract: Create target directory if not exist
  pkg/cli/extract/extract.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1243 add support for --next flag in oc adm release new
  pkg/cli/admin/release/new.go
Labels: approved, lgtm

#1258 Bug 2000554: oc inspect: Also gather namespaces in which webhook services are running
  pkg/cli/admin/inspect/resource.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#1242 Bug 2059125: release extract: Add binary re-signing for macos arm64
  pkg/cli/admin/internal/codesign/codesign.go
  pkg/cli/admin/internal/codesign/machoresign.go
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1260 OWNERS_ALIASES: Freshen update-approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#1237 pkg/cli/admin/release/extract: Unify extraction cases
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm

#1264 pkg/cli/admin/release/extract: Don't print image metadata verification messages when extracting to stdout
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#1265 oc debug,version: minor todo improvements
  pkg/cli/debug/debug.go
  pkg/cli/version/version.go
Labels: approved, lgtm

#1268 OCPBUGS-2495: pkg/cli/login: Warn, but do not fail, on surprise project-list errors
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1270 Bug 2015119: bump(k8s.io/kubectl) to pick up k/k#110764
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go
  vendor/k8s.io/kubectl/pkg/cmd/run/run.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1269 Bug 2078694: New-App Using Git via SSH
  pkg/helpers/newapp/app/sourcelookup.go
Labels: approved, lgtm

#1267 Do not try to load plugins for cobra commands
  pkg/cli/cli.go
Labels: approved, lgtm

#1272 use correct namespace with sample templates
  pkg/helpers/newapp/cmd/newapp.go
Labels: approved, lgtm

#1263 Bug 2093046: oc debug: Add priorityClassName into node debugging pod template
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1277 remove support for empty files and stdout in oc registry login
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm

#1280 Promote ardaguclu to oc approver
  OWNERS_ALIASES
Labels: approved, lgtm
