Repository openshift/oc, pull requests merged in 2022-01, with the labels that each got.

#1008 Bug 2034889: Fix another prune panic
  pkg/cli/admin/prune/deployments/data.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1010 Bug 2035393: properly handle --dry-run=server
  contrib/completions/bash/oc
  pkg/cli/set/buildhook.go
  pkg/cli/set/buildsecret.go
  pkg/cli/set/data.go
  pkg/cli/set/deploymenthook.go
  pkg/cli/set/env.go
  pkg/cli/set/imagelookup.go
  pkg/cli/set/probe.go
  pkg/cli/set/routebackends.go
  pkg/cli/set/triggers.go
  pkg/cli/set/volume.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1014 Bug 1992596: Remove admin bashcomp func
  pkg/cli/admin/oadm_bashcomp_func.go
  pkg/cli/cli.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1011 Bug 2036940: allow empty files and stdout in oc registry login
  pkg/cli/registry/login/login.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1015 Bug 2036826: Fix prune deploy resolver
  pkg/cli/admin/prune/deployments/data.go
  pkg/cli/admin/prune/deployments/data_test.go
  pkg/cli/admin/prune/deployments/deployments.go
  pkg/cli/admin/prune/deployments/resolvers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1018 Ignore VSCode files
  .gitignore
Labels: approved, lgtm, bugzilla/valid-bug

#1019 Bug 2036826: Improved prune deployments
  pkg/cli/admin/prune/deployments/data.go
  pkg/cli/admin/prune/deployments/data_test.go
  pkg/cli/admin/prune/deployments/resolvers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1020 Bug 2039491: Remove `git://` from new-app tests
  pkg/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
  pkg/cli/admin/buildchain/test/single-namespace-bcs.yaml
  pkg/helpers/describe/projectstatus_test.go
  pkg/helpers/graph/genericgraph/test/new-project-deployed-app.yaml
  pkg/helpers/graph/genericgraph/test/new-project-no-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-one-build.yaml
  pkg/helpers/graph/genericgraph/test/new-project-two-deployment-configs.yaml
  pkg/helpers/newapp/cmd/newapp_test.go
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#994 Bug 2039311: Add support for build csi volume source
  go.mod
  go.sum
  pkg/helpers/describe/describer.go
  pkg/helpers/describe/describer_test.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml-patch
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/golang.org/x/net/http2/server.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/autoscaling/v2beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/types.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1beta1/types.go
  vendor/k8s.io/api/flowcontrol/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1028 Bug 1990014: Throw error when debugging Windows nodes
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1029 Bug 2038160: Inform user about inability to schedule a debug pod
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1016 Bug 2038930: properly handle --dry-run=server
  contrib/completions/bash/oc
  pkg/cli/set/buildhook.go
  pkg/cli/set/buildsecret.go
  pkg/cli/set/data.go
  pkg/cli/set/deploymenthook.go
  pkg/cli/set/env.go
  pkg/cli/set/imagelookup.go
  pkg/cli/set/probe.go
  pkg/cli/set/routebackends.go
  pkg/cli/set/triggers.go
  pkg/cli/set/volume.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#918 Bug 1999246: adm catalog mirror should ignore .indexignore files
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/testdata/test-declcfg/.indexignore
  pkg/cli/admin/catalog/testdata/test-declcfg/README.md
Labels: approved, lgtm, lifecycle/rotten, bugzilla/valid-bug, bugzilla/severity-medium

#851 Bug 1972962: Add validation for max-icsp-size flag
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
Labels: approved, lgtm, lifecycle/rotten, bugzilla/valid-bug, bugzilla/severity-low

#1030 Bug 2039359: Fix adm prune rs orphans
  pkg/cli/admin/prune/deployments/data.go
  pkg/cli/admin/prune/deployments/data_test.go
  pkg/cli/admin/prune/deployments/deployments.go
  pkg/cli/admin/prune/deployments/prune.go
  pkg/cli/admin/prune/deployments/prune_test.go
  pkg/cli/admin/prune/deployments/resolvers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1026 Bug 1976894: Idling a StatefulSet seems to work however accessing the Services Route does not wake up the application ("Application is not available" error page is returned).
  pkg/cli/idle/idle.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1013 Bug 2035717: Enhancing the output provided when backup collections are attempted
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/summary.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
