Repository openshift/oc, pull requests merged in 2022-03, with the labels that each got.

#1072 OSDOCS-3257: Adding in new metadata requirement for docs
  hack/clibyexample/template
  hack/clibyexample/template-admin
Labels: approved, lgtm

#1081 Add support for batch/v1 CronJob
  pkg/cli/debug/debug.go
Labels: approved, lgtm

#1059 Bug 2052578: reuse SourceRepository.DetectAuth during argument classification for consistent interaction with private source repositories
  pkg/helpers/newapp/app/sourcelookup.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1085 Bug 2056122: expose --keep-startup flag for oc debug
  contrib/completions/bash/oc
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1086 Bug 2049889: logging / help improvements around 'oc new-app --search'
  pkg/cli/newapp/newapp.go
  pkg/helpers/newapp/app/dockerimagelookup.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1034 Bug 2045008: bump discovery burst
  pkg/cli/cli.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1052 Bug 2051267: pkg/cli/admin/upgrade: Mention --allow-explicit-upgrade next step when appropriate
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#1078 Bug 2056893: pkg/cli/admin/upgrade: Drop --to-image help warning
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1082 Bug 2057101: remove klog format and update messages for docker config deprecation
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1046 Add Nutanix platform
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm

#1060 [release-4.9] Bug 2051626: bump(k8s.io/*) v0.22.6
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/golang.org/x/net/http2/README
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go
  vendor/k8s.io/component-base/metrics/options.go
  vendor/k8s.io/kubectl/pkg/cmd/cmd.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_docker.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1088 pkg/cli/admin/upgrade: Mention channel choices
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1056 [release-4.10] Bug 2049427: Enhancing the output provided when backup collections are attempted
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/summary.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1077 Allow triggers on batch/v1 CronJobs
  pkg/cli/set/triggers.go
Labels: approved, ok-to-test, lgtm

#1091 Obtain OpenShift version from ClusterVersion resource
  pkg/cli/version/version.go
Labels: approved, lgtm

#1099 pkg/cli/admin/mustgather: label must-gather ns as privileged
  go.mod
  go.sum
  pkg/cli/admin/mustgather/mustgather.go
  vendor/k8s.io/pod-security-admission/LICENSE
  vendor/k8s.io/pod-security-admission/api/attributes.go
  vendor/k8s.io/pod-security-admission/api/constants.go
  vendor/k8s.io/pod-security-admission/api/doc.go
  vendor/k8s.io/pod-security-admission/api/helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#1102 Fix component name for oc
  OWNERS
Labels: approved, lgtm
