Repository openshift/oc, pull requests merged in 2022-06, with the labels that each got.

#1156 Bug 2087103: pkg/cli/admin/upgrade: "Updating to" -> "Requesting update to"
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1159 *: add relevant code owners for catalog alias
  OWNERS_ALIASES
Labels: approved, lgtm, bugzilla/valid-bug

#1152 Bug 2088483: update 'oc adm catalog mirror' command to accept --continue-on-error flag
  pkg/cli/admin/catalog/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1167 Bug 2090266: add --filter-by-os support in oc adm release extract and linux/amd64 for getting IS during mirror
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1093 Bug 1999891: bubble errors which happen prior to collection to BackupGathering
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1168 Bug 2090692: fix version from 1.24.0 beta to 1.24.1
  Makefile
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1169 Bug 1823143: add --icsp-file option to adm release subcommands
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#883 Bug 1957668: show console URL when asking for Authentication
  pkg/helpers/tokencmd/basicauth.go
  pkg/helpers/tokencmd/basicauth_test.go
  pkg/helpers/tokencmd/negotiator_sspi.go
  pkg/helpers/tokencmd/negotiator_sspi_unsupported.go
  pkg/helpers/tokencmd/request_token.go
  pkg/version/server_version.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1087 Bug 2057633: add validations for a pod & container to rsync
  pkg/cli/rsync/copy_rsync.go
  pkg/cli/rsync/util.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1170 Bug 2095584: Backport `oc adm catalog mirror` --continue-on-error flag
  contrib/completions/bash/oc
  pkg/cli/admin/catalog/mirror.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1174 Bug 2096855: extract linux/amd64 to read release metadata
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1177 Bug 2100138: Add json support for release info bug printing
  pkg/cli/admin/release/bug.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1178 Bug 2015321: Add destdir special character validation in must-gather
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1179 Bug 1905850: add a new option for checking a subresource to oc adm policy who-can
  pkg/cli/admin/policy/who_can.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
