Repository openshift/oc, pull requests merged in 2022-04, with the labels that each got.

#1100 Introduce Jira defects into release info
  pkg/cli/admin/release/bug.go
  pkg/cli/admin/release/bug_test.go
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/git_test.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#1101 Use ServerGroupResources instead deprecated ServerResources
  pkg/cli/admin/migrate/migrator.go
Labels: approved, lgtm

#829 Bug 1823143: wire ICSP lookups to oc image info
  contrib/completions/bash/oc
  pkg/cli/image/image.go
  pkg/cli/image/info/info.go
  pkg/cli/image/strategy/explicit.go
  pkg/cli/image/strategy/explicit_test.go
  pkg/cli/image/strategy/onerror.go
  pkg/cli/image/strategy/onerror_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1057 [release-4.9] Bug 2051944: Enhancing the output provided when backup collections are attempted
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/summary.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1108 Bug 2041454: Validate reference-policy for import-image command
  pkg/cli/importimage/importimage.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1109 Add --keep-manifest-list support to `oc adm release *` commands
  contrib/completions/bash/oc
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
  pkg/cli/image/append/append.go
  pkg/cli/image/append/dryrun.go
  pkg/cli/image/append/scratch.go
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm

#1111 Bug 2075647: pkg/cli/admin/upgrade: Use PATCH instead of POST for spec updates
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1106 Bug 2073113: do not report docker conf deprecation warning when the docker is not available
  pkg/cli/image/manifest/dockercredentials/auth_resolver.go
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1032 adm inspect: delete unused pod URL getting code
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/port_forward.go
Labels: approved, lgtm

#1110 Bug 2071614: Remove network CRDs scheme registration
  cmd/oc/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1116 Bug 2007647: Add squash-merge support into oc adm release info
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/git_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
