Repository openshift/oc, pull requests merged in 2022-08, with the labels that each got.

#1215 bug 2095708: oc adm inspect: check a resource exists before its inspection
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1217 Bug 2111537: (image info): Introduce show-multiarch flag
  pkg/cli/image/info/info.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1218 Bug 2108307: Set HostIPC to true when debugging node
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1196 [release-4.11] Bug 2103638: Use from-release as based image when base digest is invalid
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1224 Bug 2112934: Add servicemonitors into common namespaces for inspection
  pkg/cli/admin/inspect/namespace.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1227 [release-4.10] bug 2116526: oc adm inspect: check a resource exists before its inspection
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/util.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
