Repository openshift/oc, pull requests merged in 2023-12, with the labels that each got.

#1612 OCPBUGS-24375: Overwrite template's namespace with the explicit one
  pkg/cli/process/process.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1619 OCPBUGS-24225: Remove deprecated password defaulting in default config flag
  pkg/cli/cli.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1628 OCPBUGS-25021: Bump ocp images to 4.16 in addition to go 1.21
  .ci-operator.yaml
  go.mod
  go.sum
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  images/deployer/Dockerfile.rhel
  images/tools/Dockerfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1632 OCPBUGS-23386: Generate FIPS compatible RHEL9 oc binary
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1602 NO-JIRA: Migrate from deprecated ioutils to relevant libraries
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/groups/examples/examples_test.go
  pkg/cli/admin/groups/sync/sync.go
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/inspect_test.go
  pkg/cli/admin/migrate/icsp/icsp.go
  pkg/cli/admin/prune/auth/cluster_role_test.go
  pkg/cli/admin/prune/auth/group_test.go
  pkg/cli/admin/prune/auth/role_test.go
  pkg/cli/admin/prune/auth/user_test.go
  pkg/cli/admin/prune/imageprune/prune_test.go
  pkg/cli/admin/prune/images/images.go
  pkg/cli/admin/prune/images/images_test.go
  pkg/cli/admin/release/bug.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/new.go
  pkg/cli/admin/verifyimagesignature/verify-signature.go
  pkg/cli/deployer/strategy/recreate/recreate.go
  pkg/cli/deployer/strategy/rolling/rolling.go
  pkg/cli/deployer/strategy/support/lifecycle_test.go
  pkg/cli/image/append/append.go
  pkg/cli/image/archive/archive.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/image/serve/serve.go
  pkg/cli/newapp/newapp.go
  pkg/cli/newbuild/newbuild.go
  pkg/cli/observe/observe.go
  pkg/cli/recycle/recycle_test.go
  pkg/cli/recycle/walker_test.go
  pkg/cli/rsync/copy_rsyncd.go
  pkg/cli/rsync/copy_tar.go
  pkg/cli/startbuild/startbuild.go
  pkg/cli/startbuild/startbuild_test.go
  pkg/helpers/describe/projectstatus_test.go
  pkg/helpers/file/fileutil.go
  pkg/helpers/graph/genericgraph/test/runtimeobject_nodebuilder.go
  pkg/helpers/groupsync/grouppruner_test.go
  pkg/helpers/groupsync/groupsyncer_test.go
  pkg/helpers/groupsync/ldap/ldap.go
  pkg/helpers/groupsync/rfc2307/ldapinterface_test.go
  pkg/helpers/groupsync/syncerror/handler_test.go
  pkg/helpers/image/credentialprovider/config.go
  pkg/helpers/image/credentialprovider/config_test.go
  pkg/helpers/image/dockerlayer/add/add.go
  pkg/helpers/newapp/app/env.go
  pkg/helpers/newapp/app/sourcelookup.go
  pkg/helpers/newapp/newapptest/newapp_test.go
  pkg/helpers/source-to-image/cmd/test/cmd.go
  pkg/helpers/source-to-image/fs/fs.go
  pkg/helpers/source-to-image/git/testhelpers.go
  pkg/helpers/source-to-image/tar/tar.go
  pkg/helpers/source-to-image/tar/tar_test.go
  tools/gendocs/gendocs/gendocs.go
  tools/genman/gen_man.go
Labels: approved, lgtm, jira/valid-reference

#1643 OCPBUGS-25703: validate tag name on creation
  pkg/cli/tag/tag.go
  pkg/cli/tag/tag_test.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1644 NO-JIRA: oc adm prune images: fix --certificate-authority flag name in validation code
  pkg/cli/admin/prune/images/images.go
Labels: approved, lgtm, jira/valid-reference

#1642 OTA-492: pkg/cli/admin/upgrade/rollback: New rollback command
  pkg/cli/admin/upgrade/rollback/rollback.go
  pkg/cli/admin/upgrade/rollback/rollback_test.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference
