Repository openshift/oc, pull requests merged in 2023-01, with the labels that each got.

#1289 IR-260: Add CLI flag to set ImportMode when importing a tag
  pkg/cli/importimage/importimage.go
  pkg/cli/importimage/importimage_test.go
Labels: approved, lgtm

#1312 IR-261: Add --import-mode to 'tag'
  pkg/cli/tag/tag.go
  pkg/cli/tag/tag_test.go
Labels: approved, lgtm, qe-approved

#1321 Enable Changelog to output in JSON
  pkg/cli/admin/release/bug.go
  pkg/cli/admin/release/bug_test.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#1320 OCPBUGS-5010: Remove must-gather pod after it completes when explicit namespace is used
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1322 WRKLDS-629: release run-namspace functionality
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm

#1326 Removing unwanted character from changelog output
  pkg/cli/admin/release/info.go
Labels: approved, lgtm

#1325 OCPBUGS-6011: Fix kube version from 1.24.1 to 1.25.2
  Makefile
  hack/verify-kube-version.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1287 OCPBUGS-3473: oc adm release new: allow specifying crio and kernel versions
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
