Repository openshift/oc, pull requests merged in 2023-11, with the labels that each got.

#1594 NO-JIRA: Drop the experimental info for registry login and must-gather commands
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/registry/login/login.go
Labels: approved, lgtm, jira/valid-reference

#1595 OTA-1035: Allow testing `adm upgrade status` on mock data
  pkg/cli/admin/upgrade/status/examples/README.md
  pkg/cli/admin/upgrade/status/examples/not-upgrading-co.yaml
  pkg/cli/admin/upgrade/status/examples/not-upgrading-cv.yaml
  pkg/cli/admin/upgrade/status/examples/not-upgrading.output
  pkg/cli/admin/upgrade/status/examples_test.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1599 [release-4.13] AUTH-443: Add OAuth2 Authorization Code Grant Flow for login
  go.mod
  go.sum
  pkg/cli/login/login.go
  pkg/cli/login/loginoptions.go
  pkg/cli/login/loginoptions_test.go
  pkg/helpers/authchallengers/negotiate.go
  pkg/helpers/authchallengers/negotiate_helpers.go
  pkg/helpers/authchallengers/negotiator_gssapi.go
  pkg/helpers/authchallengers/negotiator_gssapi_unsupported.go
  pkg/helpers/authchallengers/negotiator_sspi.go
  pkg/helpers/authchallengers/negotiator_sspi_unsupported.go
  pkg/helpers/authchallengers/negotiator_test.go
  pkg/helpers/tokencmd/basicauth_test.go
  pkg/helpers/tokencmd/negotiator_sspi_unsupported.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/callback_server.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/challengehandlers/basicauth.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/challengehandlers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/challengehandlers/multi.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/request_token.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_freebsd.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_netbsd.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1533 WRKLDS-860: Add volume usage percentage checker script in must-gather's gather container
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1596 WRKLDS-908: Promote some experimental commands, deprecate others
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/image/serve/serve.go
  pkg/cli/registry/info/info.go
  pkg/cli/set/data.go
  pkg/cli/set/imagelookup.go
Labels: approved, lgtm, jira/valid-reference

#1603 NO-JIRA: Add client version in must-gather summary
  pkg/cli/admin/mustgather/summary.go
Labels: approved, lgtm, jira/valid-reference

#1601 OCPBUGS-23071: Mention inspection completion in the error message
  pkg/cli/admin/inspect/inspect.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1597 OTA-1035: `adm upgrade status` Add control plane update status
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1550 ACM-7713: Skip related objects which are invalid
  pkg/cli/admin/inspect/resource.go
Labels: approved, lgtm, jira/valid-reference

#1609 ART-8372: el7 version of oc in 4.11
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
