Repository openshift/oc, pull requests merged in 2023-04, with the labels that each got.

#1361 append: expose keep-manifest-list option and preserve manifestlist when appending to specific arch images
  pkg/cli/image/append/append.go
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm

#1367 Remove already deprecated adm create-kubeconfig command
  pkg/cli/admin/admin.go
  pkg/cli/admin/createkubeconfig/create_kubeconfig.go
Labels: approved, lgtm

#1311 OCPBUGS-1115: Use linux/arch when user's OS isn't in manifests
  pkg/cli/image/extract/extract.go
  pkg/cli/image/manifest/errors.go
  pkg/cli/image/manifest/manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1389 [OCPNODE-1581] adm catalog mirror generates idms manifest
  pkg/cli/admin/catalog/mirror.go
  pkg/cli/admin/catalog/mirror_test.go
Labels: approved, lgtm

#1393 OCPBUGS-10843: oc debug unique pod name
  pkg/cli/debug/debug.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1335 OCPBUGS-8004: Fix bug when recreating an index with fewer images
  pkg/cli/image/manifest/manifest.go
Labels: approved, ok-to-test, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1362 Support OCI manifest lists in image mirror
  pkg/cli/image/manifest/manifest.go
Labels: approved, ok-to-test, lgtm

#1400 replace trimLeft with trimPrefix
  pkg/cli/admin/prune/imageprune/helper_test.go
Labels: approved, ok-to-test, lgtm

#1181 pkg/cli/admin/upgrade: Clarify client-side vs. server-side docs
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1406 OCPBUGS-12143: oc login: unwrap tls.CertificateVerificationError to use x509 errors
  .ci-operator.yaml
  go.mod
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
