Repository openshift/oc, pull requests merged in 2023-06, with the labels that each got.

#1423 OCPBUGS-14340: Name containers w/'multi' when mirroring a multi release image
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1415 OCPBUGS-12793: adds a mapping for exposed ports to DockerConfig when manifest listed
  pkg/helpers/newapp/app/dockerimagelookup.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1403 OCPBUGS-11652: Extend adm node-logs to new API
  pkg/cli/admin/node/logs.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1445 add printing for new revisions
  pkg/cli/admin/ocpcertificates/monitorregeneration/clusteroperator.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/command.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/configmap.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/monitor.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/monitoring_reflector_store.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/secret.go
  pkg/cli/admin/ocpcertificates/ocp_certificates.go
Labels: approved, lgtm, jira/valid-bug

#1446 add command to produce an updated CA bundle for trusting the kube-apiserver
  pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
  pkg/cli/kubectlwrappers/ocp_config_command.go
  pkg/cli/kubectlwrappers/wrappers.go
Labels: approved, lgtm, jira/valid-bug

#1444 add a new command to wait for all clusteroperators to go stable
  pkg/cli/admin/admin.go
  pkg/cli/clusteroperator/clusteroperator.go
  pkg/cli/clusteroperator/waitforstable/command.go
  pkg/cli/clusteroperator/waitforstable/command_test.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagecontentpolicy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagedigestmirrorset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagetagmirrorset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_node.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_insightsdatagather.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug

#1454 add a command to copy content to every node
  go.mod
  go.sum
  pkg/cli/clusteroperator/clusteroperator.go
  pkg/cli/clusteroperator/copytonode/command.go
  pkg/cli/clusteroperator/copytonode/copy-pod-template.yaml
  pkg/cli/clusteroperator/copytonode/copy_to_node.go
  pkg/cli/clusteroperator/pernodepod/command.go
  pkg/cli/clusteroperator/pernodepod/per-node-namespace.yaml
  pkg/cli/clusteroperator/pernodepod/runtime.go
  pkg/cli/clusteroperator/restartkubelet/command.go
  pkg/cli/clusteroperator/restartkubelet/restart-pod-template.yaml
  pkg/cli/clusteroperator/restartkubelet/restart_kubelet.go
  pkg/helpers/conditions/conditions.go
  vendor/github.com/alessio/shellescape/.gitignore
  vendor/github.com/alessio/shellescape/.golangci.yml
  vendor/github.com/alessio/shellescape/.goreleaser.yml
  vendor/github.com/alessio/shellescape/AUTHORS
  vendor/github.com/alessio/shellescape/CODE_OF_CONDUCT.md
  vendor/github.com/alessio/shellescape/LICENSE
  vendor/github.com/alessio/shellescape/README.md
  vendor/github.com/alessio/shellescape/shellescape.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug

#1452 create command to create new adminkubeconfig
  pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
  pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
  pkg/cli/kubectlwrappers/ocp_config_command.go
Labels: approved, lgtm, jira/valid-bug

#1447 Add a command to remove older trust
  pkg/cli/admin/ocpcertificates/certregen/command.go
  pkg/cli/admin/ocpcertificates/certregen/leavesregen.go
  pkg/cli/admin/ocpcertificates/certregen/leavesregen_test.go
  pkg/cli/admin/ocpcertificates/certregen/rootregen.go
  pkg/cli/admin/ocpcertificates/certregen/rootregen_test.go
  pkg/cli/admin/ocpcertificates/ocp_certificates.go
  pkg/cli/admin/ocpcertificates/trustpurge/command.go
  pkg/cli/admin/ocpcertificates/trustpurge/trustpurge.go
  pkg/cli/admin/ocpcertificates/trustpurge/trustpurge_test.go
Labels: approved, lgtm, jira/valid-bug

#1455 tweaks needed for wait
  pkg/cli/clusteroperator/waitforstable/command.go
Labels: approved, lgtm, jira/valid-bug

#1458 add command to create new bootstrap kubeconfig for kubelet
  pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
  pkg/cli/config/kubeletbootstrapkubeconfig/new_kubelet_bootstrap_kubeconfig.go
  pkg/cli/kubectlwrappers/ocp_config_command.go
Labels: approved, lgtm, jira/valid-bug

#1462 ocpcertificates: don't make assumptions on resources not to bring pip…
  pkg/cli/admin/ocpcertificates/certregen/command.go
  pkg/cli/admin/ocpcertificates/trustpurge/command.go
Labels: jira/valid-bug

#1426 OCPNODE-1656: oc image extract: Introduce IDMS as alternative source
  pkg/cli/image/extract/extract.go
  pkg/cli/image/strategy/explicit.go
  pkg/cli/image/strategy/explicit_test.go
  pkg/cli/image/strategy/onerror.go
  pkg/cli/image/strategy/onerror_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1450 ocpcertificates: add ability to rotate MCS CA/cert
  go.mod
  go.sum
  pkg/cli/admin/ocpcertificates/ocp_certificates.go
  pkg/cli/admin/ocpcertificates/regeneratemco/command.go
  pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
  pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
  vendor/github.com/vincent-petithory/dataurl/LICENSE
  vendor/github.com/vincent-petithory/dataurl/README.md
  vendor/github.com/vincent-petithory/dataurl/dataurl.go
  vendor/github.com/vincent-petithory/dataurl/doc.go
  vendor/github.com/vincent-petithory/dataurl/lex.go
  vendor/github.com/vincent-petithory/dataurl/rfc2396.go
  vendor/github.com/vincent-petithory/dataurl/wercker.yml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug

#1467 fix directories for consistency
  pkg/cli/admin/admin.go
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/copytonode/copy-pod-template.yaml
  pkg/cli/admin/copytonode/copy_to_node.go
  pkg/cli/admin/pernodepod/command.go
  pkg/cli/admin/pernodepod/per-node-namespace.yaml
  pkg/cli/admin/pernodepod/runtime.go
  pkg/cli/admin/restartkubelet/command.go
  pkg/cli/admin/restartkubelet/restart-pod-template.yaml
  pkg/cli/admin/restartkubelet/restart_kubelet.go
  pkg/cli/admin/waitforstable/command.go
  pkg/cli/admin/waitforstable/command_test.go
  pkg/cli/clusteroperator/clusteroperator.go
Labels: approved, lgtm

#1468 add reboot-nodes
  pkg/cli/admin/admin.go
  pkg/cli/admin/rebootmachineconfigpool/command.go
  pkg/cli/admin/rebootmachineconfigpool/reboot_machine_config_pool.go
  pkg/cli/admin/rebootmachineconfigpool/restart-template.json
  pkg/cli/admin/rebootmachineconfigpool/types.go
  pkg/cli/admin/rebootmachineconfigpool/zz_generated.deepcopy.go
Labels: approved

#1341 OCPNODE-1580: Add --print-mirror-instructions to oc adm release mirror to allow idms instructions
  pkg/cli/admin/release/mirror.go
  pkg/cli/admin/release/mirror_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1471 tweak output format
  pkg/cli/admin/waitforstable/command.go
Labels: approved, lgtm

#1330 pkg/cli/admin/upgrade: Add post-period to space to some error messages
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1442 pkg/cli/admin/upgrade: Surface Recommended=Unknown more prominently
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1433 Fix the output of error prompt
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm

#1482 handle the error case of node retrieval while waiting for reboot
  pkg/cli/admin/waitfornodereboot/wait_for_node_reboot.go
Labels: approved, lgtm

#1376 OCPBUGS-10612: make registry auth prefence default to podman config locations
  pkg/cli/image/manifest/dockercredentials/auth_resolver.go
  pkg/cli/image/manifest/manifest.go
  pkg/cli/registry/login/login.go
  pkg/helpers/image/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1283 OCPBUGS-4812:[release-4.11] New-App Using Git via SSH
  pkg/helpers/newapp/app/sourcelookup.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1414 Clarify the use of the filter without keep-manifest-list
  pkg/cli/image/append/append.go
Labels: approved, ok-to-test, lgtm

#1489 [4.10] Use rhel 8 builder to match the base image
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1488 [4.10] Build separate oc binaries for rhel 7 and rhel 8
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1490 Add extraction for rhel7 oc
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1419 Correct incorrect command in observe command
  pkg/cli/observe/observe.go
Labels: approved, lgtm

#1464 OCPBUGS-15012: oc image extract: idms-file flag map to IDMSFile field
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1491 [4.9] Fix oc builds
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1492 [4.8] Fix oc builds
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1493 [4.7] Fix oc builds
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1494 [4.6] Fix oc builds
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
