Repository openshift/oc, pull requests merged in 2023-10, with the labels that each got.

#1524 WINC-692: Add Windows node functionality to debug command
  pkg/cli/debug/debug.go
Labels: approved, lgtm, jira/valid-reference

#1558 Updating excluded list of unsupported oc adm commands in MicroShift
  tools/gendocs/gendocs/microshift.go
Labels: approved, lgtm

#1559 OCPBUGS-20181: Use quay redis image instead docker mysql
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1555 OCPBUGS-20063: regeneratemco: explicitly check for PlatformStatus field
  pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1571 OCPBUGS-20342: Reflect container's exit code for long running tasks not attached to terminal
  pkg/cli/debug/debug.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1572 OCPBUGS-20474: Set ImportPolicy to PreserveOriginal to honor --keep-manifest-list when mirroring a payload to an image stream
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1557 OCPBUGS-9340: pkg/cli/admin/upgrade: Warn on unrecognized subcommands
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1581 OCPBUGS-20500: Fix some commands incorrect examples
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/restartkubelet/command.go
  pkg/cli/admin/waitforstable/command.go
  pkg/cli/image/mirror/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1554 pkg/cli/admin/update: Add tech-preview 'oc adm upgrade status'
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1582 create/identity: fail gracefully when no user API exists
  pkg/cli/create/identity.go
  pkg/helpers/cmd/errors.go
Labels: approved, lgtm

#1585 oc/*: gracefully fail when user group is not configured
  pkg/cli/admin/groups/new/new.go
  pkg/cli/admin/groups/sync/prune.go
  pkg/cli/admin/groups/sync/sync.go
  pkg/cli/admin/groups/users/add.go
  pkg/cli/admin/policy/modify_roles.go
  pkg/cli/admin/prune/auth/prune_command.go
  pkg/cli/admin/verifyimagesignature/verify-signature.go
  pkg/cli/create/user.go
  pkg/cli/create/user_identity_mapping.go
  pkg/cli/whoami/whoami.go
Labels: approved, lgtm

#1583 pkg/cli/admin/upgrade/status: Add update duration
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm

#1586 OCPBUGS-20500: Add directive example to kubelet-restart command
  pkg/cli/admin/restartkubelet/command.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1588 WRKLDS-874: oc whoami: Ask from selfsubjectreview and fallback to internal oauth
  pkg/cli/whoami/whoami.go
  pkg/cli/whoami/whoami_test.go
  pkg/helpers/project/whoami.go
Labels: approved, lgtm, jira/valid-reference

#1591 Updating content type variable name for CLI docs generation
  hack/clibyexample/template
  hack/clibyexample/template-admin
Labels: approved, lgtm
