Repository openshift/oc, pull requests merged in 2023-03, with the labels that each got.

#1357 Microshift command docs
  tools/gendocs/gen_openshift_docs.go
  tools/gendocs/gendocs/gendocs.go
  tools/gendocs/gendocs/microshift.go
Labels: approved, lgtm

#1350 OCPBUGS-5949: Add subrepository support for ICSP
  pkg/cli/image/strategy/onerror.go
  pkg/cli/image/strategy/onerror_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference

#1377 OCPBUGS-10622: bump repo sclorg/s2i-ruby-container location for newapp test
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1374 OCPBUGS-1117: The architecture of oc in the cli-artifacts' /usr/bin folder should to the one of the built image
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1355 OCPBUGS-3393: Always copy the blobs if the target isn't a registry
  pkg/cli/image/mirror/mirror.go
Labels: approved, ok-to-test, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1378 Test Fix: Allow submodule using file transport with newer git
  pkg/helpers/source-to-image/git/testhelpers.go
Labels: approved, ok-to-test, lgtm

#1390 OCPBUGS-10879: Fix deprecated oc command suggestion
  pkg/helpers/graph/buildgraph/analysis/bc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1353 IR-300,IR-301: generates ImageStreamTags with import-mode when using oc new-build and oc-new-app
  pkg/cli/newapp/newapp.go
  pkg/cli/newbuild/newbuild.go
  pkg/helpers/newapp/app/builder.go
  pkg/helpers/newapp/app/componentmatch.go
  pkg/helpers/newapp/app/dockerimagelookup.go
  pkg/helpers/newapp/app/imageref.go
  pkg/helpers/newapp/app/imagestreamlookup.go
  pkg/helpers/newapp/app/pipeline.go
  pkg/helpers/newapp/cmd/newapp.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1359 OCPBUGS-8048: pkg/cli/admin/upgrade: Client-side checks for --to-multi-arch
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference
