Repository openshift/oc, pull requests merged in 2023-07, with the labels that each got.

#1402 AUTH-355: Add OAuth2 Authorization Code Grant Flow for login
  go.mod
  go.sum
  pkg/cli/login/login.go
  pkg/cli/login/loginoptions.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_freebsd.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_netbsd.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1497 OCPBUGS-15776: mcs cert: account for environments that use IP directly
  pkg/cli/admin/ocpcertificates/regeneratemco/command.go
  pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
  pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1456 Add tls-server-name when property exists in kubeconfig
  pkg/helpers/kubeconfig/smart_merge.go
Labels: approved, ok-to-test, lgtm

#1499 OCPBUGS-16009: reboot: set ignition version to 3.1
  pkg/cli/admin/rebootmachineconfigpool/restart-template.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1404 OTA-994: pkg/cli/admin/release/extract: Centralize manifest extraction
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/mirror.go
Labels: approved, lgtm, jira/valid-reference

#1515 Bump k8s packages to 1.27.4
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/wait/loop.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kubectl/pkg/explain/v2/funcs.go
  vendor/k8s.io/kubectl/pkg/explain/v2/templates/plaintext.tmpl
  vendor/modules.txt
Labels: approved, lgtm

#1513 login: improve usage message for --web option
  pkg/cli/login/login.go
Labels: approved, lgtm

#1517 Fix typo in /var/log folder
  pkg/cli/admin/node/logs.go
Labels: approved, lgtm

#1519 pkg/cli/admin/upgrade: Newlines after --allow-upgrade-with-warnings errors
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm

#1520 OCPBUGS-16735: Truncate existing files when writing from inspect
  pkg/cli/admin/inspect/writer.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1505 [release-4.10] OCPBUGS-16060: mcs cert: account for environments that use IP directly
  pkg/cli/admin/ocpcertificates/regeneratemco/command.go
  pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
  pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
