Repository openshift/oc, pull requests merged in 2023-09, with the labels that each got.

#1534 OCPBUGS-15772: Decouple new-app and set commands scheme from global scheme
  cmd/oc/oc.go
  cmd/oc/oc_test.go
  pkg/cli/newapp/newapp.go
  pkg/cli/newapp/scheme.go
  pkg/cli/rollout/cancel.go
  pkg/cli/rollout/retry.go
  pkg/cli/set/buildhook.go
  pkg/cli/set/buildsecret.go
  pkg/cli/set/data.go
  pkg/cli/set/deploymenthook.go
  pkg/cli/set/env.go
  pkg/cli/set/helper.go
  pkg/cli/set/imagelookup.go
  pkg/cli/set/probe.go
  pkg/cli/set/routebackends.go
  pkg/cli/set/scheme.go
  pkg/cli/set/triggers.go
  pkg/cli/set/volume.go
  pkg/helpers/newapp/app/templatelookup.go
  pkg/helpers/newapp/cmd/newapp.go
  pkg/helpers/newapp/scheme.go
  pkg/helpers/scheme/scheme.go
Labels: approved, tide/merge-method-squash, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1548 OCPBUGS-19517: remove unsupported commands from microshift docs
  tools/gendocs/gendocs/microshift.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1552 WRKLDS-537: oc adm release info: Add --first-parent to git log for simplification
  pkg/cli/admin/release/git.go
Labels: approved, lgtm, jira/valid-reference
