Repository openshift/oc, pull requests merged in 2024-06, with the labels that each got.

#1793 NO-JIRA: Update comment about using OpenFileSequential
  pkg/cli/image/archive/archive.go
Labels: approved, lgtm, jira/valid-reference

#1791 NO-JIRA: pkg/helpers: remove legacy pkg
  pkg/helpers/describe/deployments.go
  pkg/helpers/describe/describer.go
  pkg/helpers/graph/genericgraph/test/runtimeobject_nodebuilder.go
  pkg/helpers/graph/genericgraph/test/wrong-named-port.yaml
  pkg/helpers/graph/kubegraph/edges.go
  pkg/helpers/legacy/apps.go
  pkg/helpers/legacy/authorization.go
  pkg/helpers/legacy/build.go
  pkg/helpers/legacy/doc.go
  pkg/helpers/legacy/image.go
  pkg/helpers/legacy/install.go
  pkg/helpers/legacy/network.go
  pkg/helpers/legacy/oauth.go
  pkg/helpers/legacy/project.go
  pkg/helpers/legacy/quota.go
  pkg/helpers/legacy/route.go
  pkg/helpers/legacy/security.go
  pkg/helpers/legacy/template.go
  pkg/helpers/legacy/user.go
  pkg/helpers/newapp/app/pipeline.go
Labels: approved, lgtm, jira/valid-reference

#1794 [release-4.16] OCPBUGS-33917: add alert data to upgrade health in oc adm upgrade status
  pkg/cli/admin/inspectalerts/inspectalerts.go
  pkg/cli/admin/upgrade/status/alerts.go
  pkg/cli/admin/upgrade/status/alerts_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/mockresources.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1797 OCPBUGS-34877: Ignore pruning when deployment points to replicationcontroller
  pkg/cli/admin/prune/deployments/data.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1798 OCPBUGS-35201: Bump joelanford/ignore to bump go-git to 5.11.0
  go.mod
  go.sum
  vendor/github.com/elazarl/goproxy/README.md
  vendor/github.com/elazarl/goproxy/ctx.go
  vendor/github.com/elazarl/goproxy/dispatcher.go
  vendor/github.com/elazarl/goproxy/doc.go
  vendor/github.com/elazarl/goproxy/https.go
  vendor/github.com/elazarl/goproxy/proxy.go
  vendor/github.com/elazarl/goproxy/signer.go
  vendor/github.com/elazarl/goproxy/websocket.go
  vendor/github.com/go-git/gcfg/.gitignore
  vendor/github.com/go-git/gcfg/Makefile
  vendor/github.com/go-git/gcfg/go1_0.go
  vendor/github.com/go-git/gcfg/go1_2.go
  vendor/github.com/go-git/gcfg/read.go
  vendor/github.com/go-git/gcfg/scanner/scanner.go
  vendor/github.com/go-git/gcfg/set.go
  vendor/github.com/go-git/go-billy/v5/Makefile
  vendor/github.com/go-git/go-git/v5/internal/path_util/path_util.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/encoder.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/format.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/section.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/gitignore/dir.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/gitignore/pattern.go
  vendor/github.com/go-git/go-git/v5/utils/ioutil/common.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1790 OCPBUGS-31848: don't manually delete must-gather's cluster role binding
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1742 OCPBUGS-33897: `upgrade status`: control plane completion estimate
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1807 OCPBUGS-36183: pkg/cli/admin/prune/renderedmachineconfigs: 'Error dry-run deleting'
  pkg/cli/admin/prune/renderedmachineconfigs/renderedmachineconfigs.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference
