Repository openshift/oc, pull requests merged in 2024-03, with the labels that each got.

#1694 OCPBUGS-30162: Introduce --issuer-url flag in oc login
  pkg/cli/login/login.go
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1695 OCPBUGS-30244: Add images mismatching kubectl version into warning to track
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1680 OCPBUGS-30212: oc adm catalog mirror: use ToSlash and FromSlash to unify the path separators
  pkg/cli/image/extract/extract.go
  pkg/cli/image/imagesource/file.go
  pkg/cli/image/imagesource/file_unix.go
  pkg/cli/image/imagesource/file_windows.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1704 WRKLDS-1103: tools: extend the image with sosreport
  images/tools/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#1692 WRKLDS-1076: oc idle: Remove redundant endpoint resource modification
  pkg/cli/idle/idle.go
Labels: approved, lgtm, jira/valid-reference

#1708 WRKLDS-1128: cli/admin/release/git: use optimized git flags
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/valid-reference

#1717 OCPBUGS-31484: Remove some of newapp unit tests relying on external deprecated images
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1718 WRKLDS-1128: revert cli/admin/release/git: use optimized git flags
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/valid-reference

#1714 NO-JIRA: update featuregate diff for clusterprofiles
  go.mod
  go.sum
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/info_diff_writer.go
  vendor/github.com/opencontainers/selinux/LICENSE
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go
  vendor/github.com/opencontainers/selinux/pkg/pwalkdir/README.md
  vendor/github.com/opencontainers/selinux/pkg/pwalkdir/pwalkdir.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/deduplication.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/locationmetadata.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/locationmetadata_unsupported.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphapi/types.go
  vendor/github.com/openshift/library-go/pkg/features/feature_diff_summary.go
  vendor/github.com/openshift/library-go/pkg/features/features.go
  vendor/github.com/openshift/library-go/pkg/features/summarizer.go
  vendor/github.com/openshift/library-go/pkg/image/imageutil/helpers.go
  vendor/github.com/openshift/library-go/pkg/markdown/markdown.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/verify/verify.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1719 make output table slightly easier to read
  go.mod
  go.sum
  pkg/cli/admin/release/info_diff_writer.go
  vendor/github.com/openshift/library-go/pkg/features/feature_diff_summary.go
  vendor/github.com/openshift/library-go/pkg/features/summarizer.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
