Repository openshift/oc, pull requests merged in 2024-10, with the labels that each got.

#1890 NO-JIRA: OWNERS_ALIASES: Update the username of David Hurta
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#1889 OTA-1272: pkg/cli/admin/upgrade/recommend: Show most-recent update options
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended-cv.yaml
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended-cv.yaml
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended-cv.yaml
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-both-available-and-conditional.output
  pkg/cli/admin/upgrade/recommend/examples/README.md
  pkg/cli/admin/upgrade/recommend/examples_test.go
  pkg/cli/admin/upgrade/recommend/recommend.go
  pkg/cli/admin/upgrade/recommend/recommend_test.go
Labels: approved, lgtm, jira/valid-reference

#1894 NO-JIRA: Use suggested functions instead of deprecated ones
  go.mod
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/project/new_project.go
  pkg/cli/admin/release/extract_tools.go
  pkg/cli/admin/waitforstable/command.go
  pkg/cli/cancelbuild/cancelbuild.go
  pkg/cli/debug/debug.go
  pkg/cli/deployer/strategy/recreate/recreate.go
  pkg/cli/deployer/strategy/rolling/rolling_updater.go
  pkg/cli/image/append/dryrun.go
  pkg/cli/image/append/scratch.go
  pkg/cli/image/imagesource/file.go
  pkg/cli/image/imagesource/s3.go
  pkg/cli/login/helpers.go
  pkg/cli/login/login.go
  pkg/cli/login/loginoptions.go
  pkg/cli/newapp/newapp.go
  pkg/cli/rsh/rsh.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/modules.txt
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#1895 AGENT-966: additional rbac policy rules
  pkg/cli/admin/nodeimage/create.go
Labels: approved, lgtm, jira/valid-reference

#1896 OCPBUGS-42601: Remove redundant defaulting message in description
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1899 OCPBUGS-42775: Do not allow new line in user in create user
  pkg/cli/create/user.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1876 OCPBUGS-41642: vendor: Update openshift/api to pick up the v4.17 capability set
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machineset.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machineconfiguration/v1alpha1/types_machineconfignode.go
  vendor/github.com/openshift/api/machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1901 API-1835: gather discovery when using inspect
  pkg/cli/admin/inspect/discovery.go
  pkg/cli/admin/inspect/inspect.go
Labels: approved, lgtm, jira/valid-reference

#1902 [release-4.17] OCPBUGS-43696: Bump k8s dependencies to 1.30.5
  Makefile
  go.mod
  go.sum
  images/cli/Dockerfile.rhel
  images/tools/Dockerfile
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  vendor/github.com/openshift/library-go/pkg/config/validation/general.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/github.com/openshift/library-go/pkg/oauth/tokenrequest/request_token.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/verify/configmap.go
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/kubectl/pkg/cmd/attach/attach.go
  vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go
  vendor/k8s.io/kubectl/pkg/cmd/portforward/portforward.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1903 OCPBUGS-43513: Show node-joiner container logs when error occurs
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1900 OCPBUGS-43309: The "oc adm ocp-certificates regenerate-machine-config-server-serving-cert" command is failing
  pkg/cli/admin/ocpcertificates/regeneratemco/OWNERS
  pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
