Repository openshift/oc, pull requests merged in 2024-02, with the labels that each got.

#1679 OCPBUGS-29039: fix copy-to-node
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/pernodepod/command.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1672 [release-4.15] OCPBUGS-28204: Add RHEL9 and RHEL8 based oc as new targets in command extraction
  images/cli-artifacts/Dockerfile.rhel
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1681 NO-JIRA: Bump k8s dependencies to 1.29.1
  Makefile
  go.mod
  go.sum
  images/cli/Dockerfile.rhel
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/event/keys/util.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typesinternal/objectpath.go
  vendor/golang.org/x/tools/internal/versions/gover.go
  vendor/golang.org/x/tools/internal/versions/types.go
  vendor/golang.org/x/tools/internal/versions/types_go121.go
  vendor/golang.org/x/tools/internal/versions/types_go122.go
  vendor/golang.org/x/tools/internal/versions/versions_go121.go
  vendor/golang.org/x/tools/internal/versions/versions_go122.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/patcher.go
  vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1682 TRT-1503: Tools image no longer has python;adding
  images/tools/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#1536 Do not force the ancient OS version dist tag.
  Makefile
Labels: approved, lgtm, lifecycle/rotten, jira/valid-reference

#1685 NO-JIRA: Print log rather than returning an error when kubectl version mistmaches
  pkg/cli/admin/release/image_mapper.go
  pkg/cli/admin/release/image_mapper_test.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/info_test.go
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, jira/valid-reference

#1686 OCPBUGS-29210: Update some commands incorrect examples
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/ocpcertificates/certregen/command.go
  pkg/cli/admin/ocpcertificates/regeneratemco/command.go
  pkg/cli/admin/ocpcertificates/trustpurge/command.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1674 OTA-1080: pkg/cli/admin/inspectalerts: New tech-preview inspect-alerts subcommand
  OWNERS_ALIASES
  pkg/cli/admin/admin.go
  pkg/cli/admin/inspectalerts/OWNERS
  pkg/cli/admin/inspectalerts/inspectalerts.go
Labels: approved, lgtm, jira/valid-reference

#1684 NO-JIRA: Bump k8s dependencies to 1.29.1
  Makefile
  go.mod
  go.sum
  images/cli/Dockerfile.rhel
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/event/keys/util.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typesinternal/objectpath.go
  vendor/golang.org/x/tools/internal/versions/gover.go
  vendor/golang.org/x/tools/internal/versions/types.go
  vendor/golang.org/x/tools/internal/versions/types_go121.go
  vendor/golang.org/x/tools/internal/versions/types_go122.go
  vendor/golang.org/x/tools/internal/versions/versions_go121.go
  vendor/golang.org/x/tools/internal/versions/versions_go122.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/patcher.go
  vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
