Repository openshift/oc, pull requests merged in 2024-01, with the labels that each got.

#1645 NO-JIRA: Sanitize path using filepath Clean
  pkg/cli/admin/release/new.go
  pkg/cli/rsync/copy_tar.go
Labels: approved, lgtm, jira/valid-reference

#1551 OCPBUGS-19807: pkg/cli/admin/release/extract: Log a warning on --credentials-requests without --included
  pkg/cli/admin/release/extract.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1636 OTA-1087: Add upgade health section to `adm update status`
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples_test.go
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1647 OCPBUGS-25461: Add RHEL9 and RHEL8 based oc as new targets in command extraction
  images/cli-artifacts/Dockerfile.rhel
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1651 NO-JIRA: report kubectl version to the release controller
  hack/verify-kube-version.sh
  images/cli/Dockerfile.rhel
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, jira/valid-reference

#1649 OCPBUGS-26599: release-4.11: use correct namespace with sample templates
  pkg/helpers/newapp/cmd/newapp.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1650 NO-ISSUE: add information about featuregate diff in a particular release
  pkg/cli/admin/release/config.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/valid-reference

#1653 WRKLDS-1010: pkg/cli/admin/inspect: use since/since-time for rotated logs
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/pod.go
Labels: approved, do-not-merge/hold, lgtm, jira/valid-reference

#1648 WRKLDS-950: add since and since-time flags to limit log collection on must-gather
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1641 WRKLDS-1012: oc adm must-gather: pull gather container logs
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, jira/valid-reference

#1654 NO-JIRA: adm update status: add TODOs to remind us to revise early decisions
  pkg/cli/admin/upgrade/status/health.go
Labels: approved, lgtm, jira/valid-reference

#1656 NO-JIRA: Consider kubectl version checks only from cli and cli-artifact images
  pkg/cli/admin/release/image_mapper.go
Labels: approved, lgtm, jira/valid-reference

#1633 CNV-37284: Add --all-images flag to must-gather
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1662 NO-JIRA: Simplified kubectl component version check
  pkg/cli/admin/release/image_mapper.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/info_test.go
Labels: approved, lgtm, jira/valid-reference

#1667 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1663 NO-JIRA: pkg/cli/admin/inspect: format RFC3339 parse error
  pkg/cli/admin/inspect/inspect.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1664 NO-JIRA: Fix --parallelism flag formatting in help
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/pernodepod/command.go
Labels: approved, lgtm, jira/valid-reference

#1666 OCPBUGS-27957: pkg/cli/admin/inspect: use since/since-time for previous container logs
  pkg/cli/admin/inspect/pod.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1671 OCPBUGS-27732: Bump joelanford/ignore to bump go-git to 5.11.0
  go.mod
  go.sum
  vendor/github.com/elazarl/goproxy/README.md
  vendor/github.com/elazarl/goproxy/ctx.go
  vendor/github.com/elazarl/goproxy/dispatcher.go
  vendor/github.com/elazarl/goproxy/doc.go
  vendor/github.com/elazarl/goproxy/https.go
  vendor/github.com/elazarl/goproxy/proxy.go
  vendor/github.com/elazarl/goproxy/signer.go
  vendor/github.com/elazarl/goproxy/websocket.go
  vendor/github.com/go-git/gcfg/.gitignore
  vendor/github.com/go-git/gcfg/Makefile
  vendor/github.com/go-git/gcfg/go1_0.go
  vendor/github.com/go-git/gcfg/go1_2.go
  vendor/github.com/go-git/gcfg/read.go
  vendor/github.com/go-git/gcfg/scanner/scanner.go
  vendor/github.com/go-git/gcfg/set.go
  vendor/github.com/go-git/go-billy/v5/Makefile
  vendor/github.com/go-git/go-git/v5/internal/path_util/path_util.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/encoder.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/format.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/config/section.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/gitignore/dir.go
  vendor/github.com/go-git/go-git/v5/plumbing/format/gitignore/pattern.go
  vendor/github.com/go-git/go-git/v5/utils/ioutil/common.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1669 OCPBUGS-28540: Copy oc.rhel8 instead of symlink
  images/cli-artifacts/Dockerfile.rhel
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
