Repository openshift/oc, pull requests merged in 2024-07, with the labels that each got.

#1811 WRKLDS-1310: pkg/cli/admin/mustgather: GA since and since-time flags
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-reference

#1812 OCPBUGS-36525: Bump k8s to 1.30.2
  Makefile
  go.mod
  go.sum
  images/cli/Dockerfile.rhel
  images/tools/Dockerfile
  pkg/helpers/newapp/docker/dockerfile/dockerfile.go
  pkg/helpers/newapp/docker/dockerfile/dockerfile_test.go
  vendor/github.com/containerd/typeurl/v2/.gitignore
  vendor/github.com/containerd/typeurl/v2/LICENSE
  vendor/github.com/containerd/typeurl/v2/README.md
  vendor/github.com/containerd/typeurl/v2/doc.go
  vendor/github.com/containerd/typeurl/v2/types.go
  vendor/github.com/moby/buildkit/AUTHORS
  vendor/github.com/moby/buildkit/frontend/dockerfile/parser/directives.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/parser/errors.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/parser/line_parsers.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/parser/parser.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/parser/split_command.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/shell/envVarTest
  vendor/github.com/moby/buildkit/frontend/dockerfile/shell/equal_env_unix.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/shell/equal_env_windows.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go
  vendor/github.com/moby/buildkit/frontend/dockerfile/shell/wordsTest
  vendor/github.com/moby/buildkit/util/stack/generate.go
  vendor/github.com/moby/buildkit/util/stack/stack.go
  vendor/github.com/moby/buildkit/util/stack/stack.pb.go
  vendor/github.com/moby/buildkit/util/stack/stack.proto
  vendor/github.com/pkg/profile/.travis.yml
  vendor/github.com/pkg/profile/README.md
  vendor/github.com/pkg/profile/mutex.go
  vendor/github.com/pkg/profile/mutex17.go
  vendor/github.com/pkg/profile/profile.go
  vendor/github.com/pkg/profile/trace.go
  vendor/github.com/pkg/profile/trace16.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1813 no-jira: Extend the kube version check for images/tools/Dockerfile
  hack/verify-kube-version.sh
Labels: approved, lgtm, jira/valid-reference

#1816 OCPBUGS-36328: Set required-scc annotation to privileged for node debug pods
  pkg/cli/debug/debug.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1806 OCPBUGS-35994: pkg/cli/admin/upgrade/rollback: Drop this command
  pkg/cli/admin/upgrade/rollback/rollback.go
  pkg/cli/admin/upgrade/rollback/rollback_test.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1792 : MULTIARCH-4568: Inject ReleaseArch into openshift-install
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, jira/valid-reference

#1818 [release-4.15] OCPBUGS-36329: Set required-scc annotation to privileged for node debug pods
  pkg/cli/debug/debug.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1822 OTA-1291: upgrade status: removes custom nodes from the worker pool
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/status_test.go
Labels: approved, lgtm, jira/valid-reference

#1819 WRKLDS-1314: create image command
  pkg/cli/admin/admin.go
  pkg/cli/admin/nodeimage/OWNERS
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
  pkg/cli/admin/nodeimage/monitor.go
  pkg/cli/admin/nodeimage/nodeimage.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1821 OTA-1274,OTA-1277: upgrade status: use a table to represent node pools
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-mcp.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1827 OCPBUGS-37345: Revert "OCPBUGS-35994: pkg/cli/admin/upgrade/rollback: Drop this command"
  pkg/cli/admin/upgrade/rollback/rollback.go
  pkg/cli/admin/upgrade/rollback/rollback_test.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1826 NO-JIRA: Minor wording tweaks for CLI help
  pkg/cli/admin/copytonode/command.go
  pkg/cli/admin/node/logs.go
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/ocpcertificates/certregen/command.go
  pkg/cli/admin/ocpcertificates/monitorregeneration/command.go
  pkg/cli/admin/rebootmachineconfigpool/command.go
  pkg/cli/admin/restartkubelet/command.go
  pkg/cli/admin/waitforstable/command.go
  pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
  pkg/cli/config/kubeletbootstrapkubeconfig/new_kubelet_bootstrap_kubeconfig.go
  pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
  pkg/cli/debug/debug.go
  pkg/cli/gettoken/gettoken.go
  pkg/cli/image/mirror/mirror.go
  pkg/cli/login/login.go
  pkg/cli/version/version.go
Labels: approved, lgtm, jira/valid-reference

#1825 OTA-1291: upgrade status: removes custom nodes from the worker pool (2)
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/status_test.go
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1823 WRKLDS-1316: oc adm node-image monitor command
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
  pkg/cli/admin/nodeimage/monitor.go
  pkg/cli/admin/nodeimage/monitor_test.go
  pkg/cli/admin/nodeimage/nodeimage.go
Labels: approved, lgtm, jira/valid-reference

#1832 AGENT-854: add the required role to support platform type validation
  pkg/cli/admin/nodeimage/create.go
Labels: approved, lgtm, jira/valid-reference

#1835 WRKLDS-1316: Remove clusterversions from certificates api group
  pkg/cli/admin/nodeimage/create.go
Labels: approved, lgtm, jira/valid-reference

#1830 NO-JIRA: upgrade-status: fix a typo in README
  pkg/cli/admin/upgrade/status/examples/README.md
Labels: approved, lgtm, jira/valid-reference
