Repository openshift/oc, pull requests merged in 2024-05, with the labels that each got.

#1749 OCPBUGS-32840: Bump go-jose indirect reference to 2.6.3
  go.mod
  go.sum
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1752 WRKLDS-1251: Switch cli image to RHEL9 base image
  .ci-operator.yaml
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  pkg/cli/debug/debug.go
Labels: approved, lgtm, jira/valid-reference

#1754 OTA-1275: cli/admin/release/git: use optimized git flags
  pkg/cli/admin/release/extract.go
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/valid-reference

#1756 OCPNODE-2282: Support multiple ImageDigestMirrorSet objects in the th…
  pkg/cli/image/strategy/onerror.go
Labels: approved, lgtm, jira/valid-reference

#1751 OCPNODE-2281: Support multiple icsps in migrate icsp
  pkg/cli/admin/migrate/icsp/icsp.go
  pkg/cli/admin/migrate/icsp/icsp_test.go
Labels: approved, lgtm, jira/valid-reference

#1765 OCPBUGS-32682: Fix the retrieval of API objects with an empty name
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1767 OCPBUGS-33898: `adm update status`: Show information about the upgrade target version
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
Labels: approved, tide/merge-method-squash, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1740 OCPBUGS-33896: add alert data to upgrade health in oc adm upgrade status
  pkg/cli/admin/upgrade/status/alerts.go
  pkg/cli/admin/upgrade/status/alerts_test.go
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/mockresources.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1766 OCPBUGS-33651: Add s390x based oc into extraction target
  images/cli-artifacts/Dockerfile.rhel
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1764 OCPBUGS-33905: pkg/cli/admin/upgrade/rollback: Gate on OC_ENABLE_CMD_UPGRADE_ROLLBACK
  pkg/cli/admin/upgrade/rollback/rollback.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1763 AUTH-482: set required-scc annotation to privileged for node debug pods
  pkg/cli/debug/debug.go
Labels: approved, lgtm, jira/valid-reference

#1774 OCPBUGS-33903: Simplify output when not updating
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/not-upgrading.detailed-output
  pkg/cli/admin/upgrade/status/examples/not-upgrading.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1782 OCPBUGS-33896: `status/inspect-alerts`: handle non-200 by Thanos
  pkg/cli/admin/inspectalerts/inspectalerts.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1775 OCPBUGS-32108: stop loading legacy schemes on global scheme
  pkg/cli/create/build.go
  pkg/cli/create/clusterquota.go
  pkg/cli/create/create.go
  pkg/cli/create/deploymentconfig.go
  pkg/cli/create/identity.go
  pkg/cli/create/imagestream.go
  pkg/cli/create/imagestreamtag.go
  pkg/cli/create/route.go
  pkg/cli/create/routeedge.go
  pkg/cli/create/routepassthrough.go
  pkg/cli/create/routereenecrypt.go
  pkg/cli/create/scheme.go
  pkg/cli/create/user.go
  pkg/cli/create/user_identity_mapping.go
  pkg/cli/expose/expose.go
  pkg/cli/expose/scheme.go
  pkg/helpers/scheme/scheme.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1787 OCPBUGS-33896: `upgrade status`: polish alert insights
  pkg/cli/admin/upgrade/status/alerts.go
  pkg/cli/admin/upgrade/status/alerts_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
