Repository openshift/oc, pull requests merged in 2024-11, with the labels that each got.

#1898 WRKLDS-1320: Support PXE files with "node-image create"
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
Labels: approved, lgtm, jira/valid-reference

#1906 OCPBUGS-8259: pkg/cli/admin/upgrade: Propagate --force for --to-multi-arch
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1910 NO-JIRA: Fix newapp unit test failure by using different image
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, jira/valid-reference

#1907 OTA-902: pkg/cli/admin/upgrade/recommend: Treat Upgradeable=False as a conditional update risk
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/recommend.go
Labels: approved, lgtm, jira/valid-reference

#1909 OCPBUGS-44388: add retry in case of image pull error
  pkg/cli/admin/nodeimage/create.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1915 OTA-1224: status: simplify worker status line
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1914 NO-JIRA: adm release: cleanups
  pkg/cli/admin/release/image_mapper.go
  pkg/cli/admin/release/image_mapper_test.go
  pkg/cli/admin/release/new.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#1908 NO-ISSUE: pkg/cli/admin/upgrade/recommend: "no known issues" placeholder, etc.
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/recommend.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1882 OTA-1340: upgrade status: show updating cluster operator names in the output
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1916 AGENT-1000: improve oc adm node-image output
  pkg/cli/admin/nodeimage/basenodeimagecommand.go
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
  pkg/cli/admin/nodeimage/monitor.go
  pkg/cli/admin/nodeimage/monitor_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1921 Revert "OCPBUGS-37344: Skip inspection of the daemonset pods running on data plane"
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/namespace.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1920 OTA-1393: status: recognize the process of migration to multi-arch
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-co.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-cv.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-mc.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-mco-deployment.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-mcp.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch-node.yaml
  pkg/cli/admin/upgrade/status/examples/to-multi-arch.detailed-output
  pkg/cli/admin/upgrade/status/examples/to-multi-arch.output
  pkg/cli/admin/upgrade/status/mockresources.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1924 OTA-1393: status: compute mcoImagePullSpec only once
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1917 NO-JIRA: adm release: simplify manifest iteration
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1926 OTA-1393: status: recognize multi-arch in target version
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/to-multi-arch.detailed-output
  pkg/cli/admin/upgrade/status/examples/to-multi-arch.output
Labels: approved, lgtm, jira/valid-reference
