Repository openshift/oc, pull requests merged in 2024-04, with the labels that each got.

#1721 OCPBUGS-31615: Add help text the behavior of filter-by-os against single image
  pkg/cli/image/info/info.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1725 WRKLDS-1171: Add openshift-install-fips target to oc release extract
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, jira/valid-reference

#1720 OCPBUGS-31498: Add OIDC specific certificate authority bundle flag
  pkg/cli/login/login.go
  pkg/cli/login/loginoptions.go
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1731 OTA-1036: `adm upgrade status`: Add control plane nodes status
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1732 OTA-1036: `adm update status`: Refactor node status
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1723 MCO-1056: MCO-1057: Implement oc adm prune machineconfigs command
  pkg/cli/admin/prune/prune.go
  pkg/cli/admin/prune/renderedmachineconfigs/OWNERS
  pkg/cli/admin/prune/renderedmachineconfigs/renderedmachineconfigs.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1735 OTA-1174: `upgrade status`: add `--detailed=nodes` that shows all nodes
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/examples/README.md
  pkg/cli/admin/upgrade/status/examples/not-upgrading.detailed-output
  pkg/cli/admin/upgrade/status/examples_test.go
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1736 OTA-1174: `upgrade status`: Expand health insights with `--detailed=health`
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, jira/valid-reference

#1739 OTA-1202: Changing the conditional risk to known issues
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference

#1738 WRKLDS-1190: oc adm must-gather: print timestamp when logging in fallback mode
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-reference

#1729 NO-JIRA: Print an error msg instead of panicking when all image manifests are filtered out
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, jira/valid-reference

#1652 OCPBUGS-20097: Migrate tools image to RHEL9
  images/recycler/Dockerfile.rhel
  images/tools/Dockerfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1741 OTA-1155: `update status`: Simplify CO status line
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
Labels: approved, lgtm, jira/valid-reference

#1737 OTA-1174: `upgrade status`: Show resources in `--details=health`
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/health.go
  pkg/cli/admin/upgrade/status/health_test.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, jira/valid-reference

#1734 OCPBUGS-32080: release: extract ccoctl.rhel8 and ccoctl.rhel9
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1746 OCPBUGS-32786: Improve error message when binary is not in target list
  pkg/cli/admin/release/extract_tools.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#1726 [release-4.15] OCPBUGS-31726: Remove some of newapp unit tests relying on external deprecated images
  pkg/helpers/newapp/newapptest/newapp_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1748 OTA-1174: `update status`: unify on `--details`
  pkg/cli/admin/upgrade/status/examples/README.md
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1744 OTA-1279: pkg/cli/admin/upgrade/status: Move Failing from free-form to updateInsight
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1753 OTA-1154: pkg/cli/admin/upgrade/status: Drop free-form Progressing output line
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference
