Repository openshift/oc, pull requests merged in 2024-08, with the labels that each got.

#1836 WRKLDS-1316: Retry and do not fail when logs cannot be updated
  pkg/cli/admin/nodeimage/monitor.go
Labels: approved, lgtm, jira/valid-reference

#1834 NO-JIRA: upgrade-status: fix HasOSImage function
  pkg/cli/admin/upgrade/status/mco/layered_pool_state.go
Labels: approved, lgtm, jira/valid-reference

#1831 OTA-1153: upgrade-status: communicate control plane completion clearly
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/controlplane_test.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
Labels: approved, lgtm, jira/valid-reference

#1837 WRKLDS-1429: Adds a guardrail for node-image commands which is supported only for Openshift version 4.17+
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
Labels: approved, lgtm, jira/valid-reference

#1829 OTA-1309: upgrade-status: test a compact cluster and a single-node cluster
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact-mc.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact-mcp.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-cv.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-mc.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-mcp.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1833 [WIP] WRKLDS-1318: flags for single node interface
  pkg/cli/admin/nodeimage/create.go
Labels: do-not-merge/work-in-progress, approved, jira/valid-reference

#1838 OTA-1292: upgrade-status: bubble up the reason for unavailable nodes
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/mco/layered_node_state.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, jira/valid-reference

#1845 OCPBUGS-32053: Add examples for some oc adm policy commands
  pkg/cli/admin/policy/modify_roles.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1844 OTA-1212: Hide or condense control plane sections once successfully updated
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/workerpool.go
Labels: approved, lgtm, jira/valid-reference

#1846 NO-JIRA: `upgrade status`: improve tests for missing annotations
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining-node.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
Labels: approved, lgtm, jira/valid-reference

#1847 OTA-1292: upgrade-status: handle expected MCD state better
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/mco/layered_node_state.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, jira/valid-reference

#1849 OTA-1292: upgrade-status: handle unschedulable nodes better
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
  pkg/cli/admin/upgrade/status/mco/layered_node_state.go
  pkg/cli/admin/upgrade/status/workerpool.go
  pkg/cli/admin/upgrade/status/workerpool_test.go
Labels: approved, lgtm, jira/valid-reference

#1848 OTA-1292: upgrade-status: handle the OS image annotation better
  pkg/cli/admin/upgrade/status/mco/layered_node_state.go
Labels: approved, lgtm, jira/valid-reference

#1853 make the idle command's scale update unconditional
  pkg/cli/idle/idle.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1857 OCPBUGS-38990: use proxy settings when required
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#1858 OTA-1309: hide the empty "Worker Upgrade" section
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/valid-reference

#1859 OTA-1153: update-status: re-title "Operator Health"
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-compact.output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output
Labels: approved, lgtm, jira/valid-reference

#1861 OCPBUGS-30658: pkg/cli/admin/upgrade: --to-latest help "next" -> "latest"
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference
