Repository openshift/oc, pull requests merged in 2025-02, with the labels that each got.

#1854 STOR-2040: CLI command to display bound pvc filesystem usage percentage
  OWNERS_ALIASES
  pkg/cli/admin/top/top.go
  pkg/cli/admin/toppvc/OWNERS
  pkg/cli/admin/toppvc/persistentvolumeclaims.go
  pkg/cli/admin/toppvc/printer.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1968 [release-4.17] OCPBUGS-49605: Address `github.com/docker/docker` CVE
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1969 NO-JIRA: Sanitize tar header name as it is used in path
  pkg/helpers/source-to-image/tar/tar.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1970 OTA-1426: pkg/cli/admin/upgrade: Check and display interesting alerts
  pkg/cli/admin/upgrade/recommend/alerts.go
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-alerts.json
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-cv.yaml
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples_test.go
  pkg/cli/admin/upgrade/recommend/mockresources.go
  pkg/cli/admin/upgrade/recommend/precheck.go
  pkg/cli/admin/upgrade/recommend/recommend.go
  pkg/cli/admin/upgrade/status/alerts.go
Labels: approved, lgtm, jira/valid-reference

#1974 OCPBUGS-50682: OCPBUGS-50683: Correct oc adm top pvc messages
  pkg/cli/admin/toppvc/persistentvolumeclaims.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1980 NO-ISSUE: pkg/cli/admin/upgrade/recommend: "Upstream" -> "Upstream update service"
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.show-outdated-releases-output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/recommend.go
Labels: approved, lgtm, jira/valid-reference

#1981 NO-ISSUE: pkg/cli/admin/upgrade/recommend: Configureable version for test fixtures
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.16.32-output
  pkg/cli/admin/upgrade/recommend/examples/README.md
  pkg/cli/admin/upgrade/recommend/examples_test.go
Labels: approved, lgtm, jira/valid-reference
