Repository openshift/oc, pull requests merged in 2025-09, with the labels that each got.

#2068 OCPBUGS-59951: must-gather: Fix usage checker for custom commands
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2084 OCPBUGS-56691: Rely on overall available disk space of the mounted volume
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#2087 OCPBUGS-59951: oc adm must-gather: Wrap gather in a session
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#2088 OCPBUGS-61063: pkg/cli/admin/upgrade/recommend: Enable precheck and accept gates
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
  pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.16.32-output
  pkg/cli/admin/upgrade/recommend/recommend.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#2080 WRKLDS-593: oc adm must-gather: Improve cleanup order
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/valid-reference, verified

#2100 OCPBUGS-59311: pkg/.../inspect: Add support for context.Context
  pkg/cli/admin/inspect/admission_webhooks.go
  pkg/cli/admin/inspect/apiextensions.go
  pkg/cli/admin/inspect/inspect.go
  pkg/cli/admin/inspect/namespace.go
  pkg/cli/admin/inspect/pod.go
  pkg/cli/admin/inspect/proxy.go
  pkg/cli/admin/inspect/resource.go
  pkg/cli/admin/inspect/route.go
  pkg/cli/admin/inspect/secret.go
  pkg/cli/admin/inspect/writer.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#2105 OCPBUGS-59311: oc adm must-gather: Add support for context
  pkg/cli/admin/mustgather/mustgather.go
  pkg/cli/admin/mustgather/mustgather_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified
