Repository openshift/oc, pull requests merged in 2025-05, with the labels that each got.

#1947 NO-JIRA: make 'oc status' compatible with bare kube
  pkg/cli/status/status.go
  pkg/helpers/describe/projectstatus.go
  pkg/helpers/describe/projectstatus_test.go
  vendor/github.com/openshift/client-go/project/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/doc.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/fake_project_client.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/fake_projectrequest.go
  vendor/modules.txt
Labels: approved, lgtm, lifecycle/rotten, jira/valid-reference

#2003 WRKLDS-1103: Adding sos.conf file for default sos config into the tools image
  images/tools/Dockerfile
  images/tools/sos.conf
Labels: approved, lgtm, qe-approved, jira/valid-reference

#2019 NO-JIRA: OCPBUGS-46604: Clarify behavior of since-time flag in oc adm must-gather command
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#2022 OCPBUGS-55220: Replace colon to hypen in the filename while extracting tar on Windows
  pkg/helpers/source-to-image/tar/tar.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#2025 OCPBUGS-56598: pkg/cli/admin/mustgather: Include ClusterVersion in fallback inspect
  pkg/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2031 OCPBUGS-49897: avoid transfering permissions when copying artifacts from node-joiner pod
  pkg/cli/admin/nodeimage/create.go
  pkg/cli/admin/nodeimage/create_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
