Repository openshift/oc, pull requests merged in 2025-04, with the labels that each got.

#1966 COS-3023: pkg/cli/admin/release/info: support generating RPM diffs
  pkg/cli/admin/release/annotations.go
  pkg/cli/admin/release/info.go
  pkg/cli/admin/release/info_test.go
  pkg/cli/admin/release/info_unix.go
  pkg/cli/admin/release/info_windows.go
Labels: approved, lgtm, jira/valid-reference

#2006 COS-3023: Fixing rpmdiff permissions when running in container
  pkg/cli/image/extract/extract.go
Labels: approved, lgtm, jira/valid-reference

#2008 NO-JIRA: `adm release new`: simplify `writePayload`
  pkg/cli/admin/release/new.go
Labels: approved, lgtm, jira/valid-reference

#2007 OCPBUGS-52164: Add the generation of initrd.addrsize and generic.ins file for ABI Day2 Artifacts
  pkg/cli/admin/nodeimage/create.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2005 OCPBUGS-53106: Get installer image from configMap for node-image command
  pkg/cli/admin/nodeimage/basenodeimagecommand.go
  pkg/cli/admin/nodeimage/mirrorbuilder.go
  pkg/cli/admin/nodeimage/mirrorbuilder_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
