Repository openshift/oc, pull requests merged in 2025-08, with the labels that each got.

#2074 OCPNODE-3557: Fixes oc debug managed by label when keep labels option is not used
  pkg/cli/debug/debug.go
  pkg/cli/debug/debug_test.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#2076 OTA-1560: pkg/cli/admin/upgrade: Promote 'recommend' to general availability
  pkg/cli/admin/upgrade/recommend/recommend.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference

#2073 OCPBUGS-60281: Fix panic in oc describe templateinstance when Secret is nil
  pkg/helpers/describe/describer.go
  pkg/helpers/describe/describer_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2075 OCPBUGS-58393: oc login: Preserve ExecProvider on oc login -u
  pkg/cli/login/loginoptions.go
  pkg/cli/login/loginoptions_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2077 OTA-1601: Better the Updating Cluster Operators table
  pkg/cli/admin/upgrade/status/controlplane.go
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node-co.yaml
  pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output
Labels: approved, lgtm, jira/valid-reference

#2063 OTA-1581: Promote `oc adm upgrade status` to general availability
  pkg/cli/admin/upgrade/status/status.go
  pkg/cli/admin/upgrade/upgrade.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#2082 NO-JIRA: Remove mentioning about IRC channel in README
  README.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#2083 OCPBUGS-60877: pkg/cli/admin/inspectalerts: Pass through --certificate-authority, etc.
  pkg/cli/admin/inspectalerts/inspectalerts.go
  pkg/cli/admin/upgrade/recommend/alerts.go
  pkg/cli/admin/upgrade/recommend/recommend.go
  pkg/cli/admin/upgrade/status/status.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2086 OCPBUGS-60989: pkg/cli/admin/release/info: Mention elided first-parent, non-merge commits
  pkg/cli/admin/release/git.go
  pkg/cli/admin/release/git_test.go
  pkg/cli/admin/release/info.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
