Repository openshift/oc, pull requests merged in 2025-01, with the labels that each got.

#1949 OCPBUGS-38975: monitor should not exit for temp api disconnect
  pkg/cli/admin/nodeimage/monitor.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1959 NO-ISSUE: admin/upgrade/status/examples/README: Document *-alerts.json
  pkg/cli/admin/upgrade/status/examples/README.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1960 OCPBUGS-49450: Address `github.com/docker/docker` CVE
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1967 [release-4.18] OCPBUGS-49604: Address `github.com/docker/docker` CVE
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
